# Generated by Django 6.0.6 on 2026-06-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Фильтры отчета'),
        ),
    ]
