# Generated by Django 6.0.6 on 2026-06-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttemplate_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='group_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='Группировка'),
        ),
    ]
