# Generated by Django 6.0.6 on 2026-06-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reporttemplate_column_labels'),
        ('users', '0002_driverprimaryregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Краткое замечание')),
                ('category', models.CharField(choices=[('interface', 'Интерфейс'), ('data', 'Данные'), ('trip', 'Рейс'), ('shift', 'Смена'), ('assignment', 'Назначение'), ('downtime', 'Простои'), ('report', 'Отчет'), ('management', 'Витрина'), ('access', 'Права и доступы'), ('next_module', 'Следующий модуль')], max_length=32, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('p0', 'P0 - блокирует пилот'), ('p1', 'P1 - исправить до запуска'), ('p2', 'P2 - можно после запуска'), ('p3', 'P3 - идея или улучшение')], default='p2', max_length=8, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('decided', 'Решение принято'), ('postponed', 'Перенесено'), ('rejected', 'Отклонено')], default='new', max_length=16, verbose_name='Статус')),
                ('screen', models.CharField(blank=True, max_length=160, verbose_name='Экран или процесс')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('decision', models.TextField(blank=True, verbose_name='Решение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_feedback_created', to='users.employee', verbose_name='Кто зафиксировал')),
            ],
            options={
                'verbose_name': 'Замечание пилота',
                'verbose_name_plural': 'Замечания пилота',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
