# Generated by Django 6.0.6 on 2026-07-29

import django.db.models.deletion
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_pilotfeedback'),
        ('shifts', '0012_watchperiod_watch_composition'),
        ('trips', '0008_trip_cancelled_at'),
        ('users', '0016_watchcomposition_employee_watch_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShiftPassportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(verbose_name='Ревизия')),
                ('schema_version', models.PositiveSmallIntegerField(verbose_name='Версия схемы паспорта')),
                ('calculator_version', models.CharField(max_length=64, verbose_name='Версия калькулятора')),
                ('source_fingerprint', models.CharField(max_length=64, verbose_name='Fingerprint источников')),
                ('payload_fingerprint', models.CharField(max_length=64, verbose_name='Fingerprint паспорта')),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Диагностический паспорт')),
                ('trigger', models.CharField(choices=[('driver_close', 'Обычное закрытие водителем'), ('service_close', 'Служебное закрытие'), ('role_switch', 'Закрытие при переключении роли'), ('source_reconcile', 'Пересчёт после изменения источников'), ('backfill', 'Ретроспективное заполнение'), ('calculator_upgrade', 'Новая версия калькулятора')], max_length=32, verbose_name='Причина формирования')),
                ('captured_late', models.BooleanField(default=False, verbose_name='Сформирован с задержкой')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформирован')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captured_driver_shift_passports', to='users.employee', verbose_name='Кем инициирован')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_snapshots', to='shifts.employeeshift', verbose_name='Смена водителя')),
            ],
            options={
                'verbose_name': 'Диагностический паспорт смены водителя',
                'verbose_name_plural': 'Диагностические паспорта смен водителей',
                'ordering': ['shift_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='DriverShiftPassportCaptureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=64, unique=True, verbose_name='Ключ запроса')),
                ('trigger', models.CharField(choices=[('driver_close', 'Обычное закрытие водителем'), ('service_close', 'Служебное закрытие'), ('role_switch', 'Закрытие при переключении роли'), ('source_reconcile', 'Пересчёт после изменения источников'), ('backfill', 'Ретроспективное заполнение'), ('calculator_upgrade', 'Новая версия калькулятора')], max_length=32, verbose_name='Причина формирования')),
                ('calculator_version', models.CharField(max_length=64, verbose_name='Версия калькулятора')),
                ('closed_at', models.DateTimeField(verbose_name='Момент закрытия смены')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('failed', 'Ошибка') , ('completed', 'Готово')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработка начата')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработка завершена')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_shift_passport_requests', to='users.employee', verbose_name='Кем инициирован')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_capture_requests', to='shifts.employeeshift', verbose_name='Смена водителя')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capture_requests', to='reports.drivershiftpassportsnapshot', verbose_name='Сформированный паспорт')),
            ],
            options={
                'verbose_name': 'Запрос на паспорт смены водителя',
                'verbose_name_plural': 'Запросы на паспорта смен водителей',
                'ordering': ['requested_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='drivershiftpassportsnapshot',
            index=models.Index(fields=['shift', '-revision'], name='driver_passport_shift_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivershiftpassportsnapshot',
            constraint=models.UniqueConstraint(fields=('shift', 'revision'), name='unique_driver_passport_shift_revision'),
        ),
        migrations.AddConstraint(
            model_name='drivershiftpassportsnapshot',
            constraint=models.UniqueConstraint(fields=('shift', 'calculator_version', 'source_fingerprint'), name='unique_driver_passport_source_version'),
        ),
        migrations.AddIndex(
            model_name='drivershiftpassportcapturerequest',
            index=models.Index(fields=['status', 'requested_at'], name='driver_passport_req_status_idx'),
        ),
    ]
