# Generated by Django 6.0.6 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_driver_shift_passport_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPeriod',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Например: Премирование за август 2026.',
                        max_length=160,
                        verbose_name='Название периода',
                    ),
                ),
                (
                    'starts_on',
                    models.DateField(
                        help_text='Начальная дата включается в расчёт.',
                        verbose_name='Считать с',
                    ),
                ),
                (
                    'ends_before',
                    models.DateField(
                        help_text=(
                            'Эта дата в расчёт не входит. Например, период '
                            '14.07–14.08 считает данные по 13.08 включительно.'
                        ),
                        verbose_name='Считать до (не включая дату)',
                    ),
                ),
                (
                    'comment',
                    models.TextField(
                        blank=True,
                        help_text=(
                            'Укажите основание, если даты замера отличаются '
                            'от обычного вахтового периода.'
                        ),
                        verbose_name='Причина или примечание',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Только включённые периоды могут использоваться '
                            'для расчёта рейтинга.'
                        ),
                        verbose_name='Используется для расчёта',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Создан',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Изменён',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Период рейтинга',
                'verbose_name_plural': 'Периоды рейтинга',
                'ordering': ['-starts_on', '-id'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            ('ends_before__gt', models.F('starts_on')),
                        ),
                        name='rating_period_end_after_start',
                    ),
                ],
            },
        ),
    ]
