# Generated by Django 6.0.6 on 2026-09-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_driver_rating_materialized_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverratingperiodmaterializedsnapshot',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], max_length=16, verbose_name='Тип смены'),
        ),
    ]
