# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Причина простоя')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Критический простой')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.equipmenttype', verbose_name='Вид техники')),
            ],
            options={
                'verbose_name': 'Причина простоя',
                'verbose_name_plural': 'Причины простоев',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Кто зафиксировал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipment', verbose_name='Техника')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='downtimes.downtimereason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Событие простоя',
                'verbose_name_plural': 'События простоев',
                'ordering': ['-started_at'],
            },
        ),
    ]
