# Generated by Django 6.0.6 on 2026-07-04 00:59

import django.db.models.deletion
from django.db import migrations, models


DOWNTIME_REASON_SETS = [
    # name, short_label, equipment_type_hint, equipment_state_code, is_critical,
    # show_for_truck_driver, show_for_excavator_operator, show_for_mechanic, sort_order
    ('Ожидание погрузки', 'Ожидание погрузки', 'Самосвал', 'waiting', False, True, False, False, 10),
    ('Ожидание разгрузки', 'Ожидание разгрузки', 'Самосвал', 'waiting', False, True, False, False, 20),
    ('Ожидание разгрузки ККД', 'Ожидание ККД', 'Самосвал', 'waiting', False, True, False, False, 21),
    ('Ожидание разгрузки СКДР', 'Ожидание СКДР', 'Самосвал', 'waiting', False, True, False, False, 22),
    ('Ожидание фронта работ', 'ОФР', None, 'waiting', False, True, False, False, 30),
    ('Заправка', 'Заправка', None, 'downtime', False, True, True, False, 40),
    ('ТО', 'ТО', None, 'maintenance', False, True, True, False, 50),
    ('Ремонт', 'Ремонт', None, 'repair', False, True, True, True, 60),
    ('Поломка', 'Поломка', None, 'breakdown', True, True, True, True, 70),
    ('БВР', 'БВР', None, 'downtime', False, True, True, False, 80),
    ('Обед', 'Обед', None, 'downtime', False, True, True, False, 90),
    ('Чистка кузова', 'Чистка кузова', 'Самосвал', 'downtime', False, True, False, False, 100),
    ('Ожидание самосвалов', 'Ожидание самосвалов', 'Экскаватор', 'waiting', False, False, True, False, 110),
    ('Зачистка забоя', 'Зачистка забоя', 'Экскаватор', 'downtime', False, False, True, False, 120),
    ('Подготовка забоя', 'Подготовка забоя', 'Экскаватор', 'downtime', False, False, True, False, 130),
    ('Перегон экскаватора', 'Перегон', 'Экскаватор', 'downtime', False, False, True, False, 140),
    ('Климатические условия', 'Погода', None, 'downtime', False, True, True, False, 150),
    ('Прочие', 'Прочие', None, 'downtime', False, True, True, False, 160),
    ('Диагностика', 'Диагностика', None, 'maintenance', False, False, False, True, 210),
    ('Текущий ремонт', 'Текущий ремонт', None, 'repair', True, False, False, True, 220),
    ('Электрика', 'Электрика', None, 'repair', True, False, False, True, 230),
    ('Гидравлика', 'Гидравлика', None, 'repair', True, False, False, True, 240),
    ('Двигатель', 'Двигатель', None, 'repair', True, False, False, True, 250),
    ('Ходовая часть', 'Ходовая', None, 'repair', True, False, False, True, 260),
    ('ТО и обслуживание', 'ТО и обслуживание', None, 'maintenance', False, False, False, True, 270),
    ('Сварочные работы', 'Сварка', None, 'repair', True, False, False, True, 280),
    ('Система охлаждения', 'Охлаждение', None, 'repair', True, False, False, True, 290),
    ('Шиномонтажные работы', 'Шиномонтаж', 'Самосвал', 'repair', False, False, False, True, 300),
    ('Программное обеспечение', 'ПО', None, 'repair', False, False, False, True, 310),
]


def seed_role_based_downtime_reasons(apps, schema_editor):
    DowntimeReason = apps.get_model('downtimes', 'DowntimeReason')
    EquipmentType = apps.get_model('references', 'EquipmentType')
    EquipmentState = apps.get_model('references', 'EquipmentState')

    equipment_types = list(EquipmentType.objects.all())
    equipment_state_by_code = {state.code: state for state in EquipmentState.objects.all()}

    def find_equipment_type(hint):
        if not hint:
            return None
        hint_lower = hint.lower()
        for equipment_type in equipment_types:
            if hint_lower in equipment_type.name.lower():
                return equipment_type
        return None

    for (
        name,
        short_label,
        equipment_type_hint,
        equipment_state_code,
        is_critical,
        show_for_truck_driver,
        show_for_excavator_operator,
        show_for_mechanic,
        sort_order,
    ) in DOWNTIME_REASON_SETS:
        DowntimeReason.objects.update_or_create(
            name=name,
            defaults={
                'short_label': short_label,
                'equipment_type': find_equipment_type(equipment_type_hint),
                'equipment_state': equipment_state_by_code.get(equipment_state_code),
                'is_critical': is_critical,
                'show_for_truck_driver': show_for_truck_driver,
                'show_for_excavator_operator': show_for_excavator_operator,
                'show_for_mechanic': show_for_mechanic,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


def unseed_role_based_downtime_reasons(apps, schema_editor):
    # Не удаляем причины: к ним могут быть привязаны события простоев.
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('downtimes', '0002_seed_mechanic_reasons'),
        ('references', '0003_remove_in_transit_and_rename_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimereason',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Причина простоя', 'verbose_name_plural': 'Причины простоев'},
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='equipment_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.equipmentstate', verbose_name='Состояние техники'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='short_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Короткая подпись для кнопки'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='show_for_excavator_operator',
            field=models.BooleanField(default=False, verbose_name='Показывать машинисту экскаватора'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='show_for_mechanic',
            field=models.BooleanField(default=False, verbose_name='Показывать механику'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='show_for_truck_driver',
            field=models.BooleanField(default=False, verbose_name='Показывать водителю самосвала'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок'),
        ),
        migrations.RunPython(seed_role_based_downtime_reasons, unseed_role_based_downtime_reasons),
    ]
