# Generated by Django 6.0.6 on 2026-08-24 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def preserve_legacy_downtime_audit(apps, schema_editor):
    DowntimeEvent = apps.get_model('downtimes', 'DowntimeEvent')
    DowntimeEvent.objects.using(schema_editor.connection.alias).update(
        recorded_by_id=F('employee_id'),
        recorded_at=F('started_at'),
    )


def clear_legacy_downtime_audit(apps, schema_editor):
    DowntimeEvent = apps.get_model('downtimes', 'DowntimeEvent')
    DowntimeEvent.objects.using(schema_editor.connection.alias).update(recorded_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_update_downtime_reason_state_semantics'),
        ('users', '0018_employee_watch_profile_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimeevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Сотрудник (совместимость отчётов)'),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Зарегистрировано'),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_downtime_events', to='users.employee', verbose_name='Кто зарегистрировал'),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='source',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('dispatcher_override', 'Служебное действие диспетчера'), ('telemetry', 'Телеметрия'), ('system', 'Система')], default='employee', max_length=32, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='subject_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_downtime_events', to='users.employee', verbose_name='Кого затрагивает'),
        ),
        migrations.RunPython(
            preserve_legacy_downtime_audit,
            reverse_code=clear_legacy_downtime_audit,
        ),
    ]
