# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('personnel_number', models.CharField(blank=True, max_length=64, verbose_name='Табельный номер')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код роли')),
                ('name', models.CharField(max_length=128, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=128, unique=True, verbose_name='Код доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Отключен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.employee', verbose_name='Сотрудник')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='users.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Доступ сотрудника',
                'verbose_name_plural': 'Доступы сотрудников',
                'ordering': ['employee__full_name', 'role__name'],
            },
        ),
    ]
