# Generated by Django 6.0.6 on 2026-06-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPrimaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная'), ('night', 'Ночная')], max_length=16, verbose_name='Смена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('dormitory_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.dormitorysection', verbose_name='Секция проживания')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_registration', to='users.employee', verbose_name='Водитель')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipment', verbose_name='Самосвал')),
            ],
            options={
                'verbose_name': 'Первичная регистрация водителя',
                'verbose_name_plural': 'Первичные регистрации водителей',
                'ordering': ['employee__full_name'],
            },
        ),
    ]
