# Generated by Django 6.0.6 on 2026-06-19 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprimaryregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dismissed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_data',
            field=models.TextField(blank=True, verbose_name='Паспортные/кадровые данные'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, upload_to='employee_photos/', verbose_name='Фото сотрудника'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residence_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rotation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Вахта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('not_activated', 'Не активирован'), ('deactivated', 'Деактивирован'), ('archived', 'В архиве'), ('dismissed', 'Уволен'), ('deleted', 'Удален')], default='not_activated', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активирован'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='primary_code_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первичный пинкод выдан'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='status',
            field=models.CharField(choices=[('not_activated', 'Не активирован'), ('activated', 'Активирован'), ('blocked', 'Заблокирован'), ('deactivated', 'Деактивирован')], default='not_activated', max_length=32, verbose_name='Статус доступа'),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action', models.CharField(max_length=128, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, max_length=128, verbose_name='Тип объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='users.employee', verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Журнал действия администратора',
                'verbose_name_plural': 'Журнал действий администратора',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('conflict_type', models.CharField(max_length=128, verbose_name='Тип конфликта')),
                ('process', models.CharField(blank=True, max_length=128, verbose_name='Процесс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('resolved', 'Решен'), ('rejected', 'Отклонен')], default='open', max_length=32, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разбора')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_conflicts', to='users.employee', verbose_name='Сотрудник')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_admin_conflicts', to='users.employee', verbose_name='Кто разобрал')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Административный конфликт',
                'verbose_name_plural': 'Административные конфликты',
                'ordering': ['-created_at'],
            },
        ),
    ]
