# Generated by Django 6.0.6 on 2026-06-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_comment_employee_dismissed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprimaryregistration',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='driverprimaryregistration',
            name='truck',
        ),
    ]
