# Generated by Django 6.0.6 on 2026-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_driverprimaryregistration_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='Должность'),
        ),
    ]
