# Generated by Django 6.0.6 on 2026-06-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_deduplicate_employee_accesses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeaccess',
            name='unique_employee_role_access',
        ),
    ]
