# Generated by Django 6.0.6 on 2026-07-17 16:02

import django.db.models.deletion
from django.db import migrations, models


SPECIALIZATIONS = (
    ('haul_truck_driver', 'Технологический самосвал', ('Самосвал',), 'driver'),
    ('excavator_operator', 'Машинист экскаватора', ('Экскаватор',), 'excavator_operator'),
    ('cargo_kdm_driver', 'Водитель КДМ', (), None),
    ('cargo_prm_driver', 'Водитель ПРМ', (), None),
    ('fuel_truck_driver', 'Водитель топливозаправщика', (), None),
    ('watch_bus_driver', 'Водитель вахтового автобуса', (), None),
    ('mobile_canteen_driver', 'Водитель передвижной столовой', (), None),
    ('light_vehicle_driver', 'Водитель легкового автомобиля', (), None),
    ('bulldozer_operator', 'Машинист бульдозера', ('Бульдозер',), None),
    ('loader_operator', 'Водитель погрузчика', ('Погрузчик',), None),
    ('grader_operator', 'Машинист автогрейдера', ('Автогрейдер',), None),
    ('roller_operator', 'Машинист катка', ('Каток',), None),
    ('mobile_crane_operator', 'Машинист автомобильного крана', ('Кран',), None),
    ('assistant_excavator_operator', 'Помощник машиниста экскаватора', (), None),
)


POSITIONS = (
    ('position_001', 'Водитель автомобиля, занятый на транспортировании горной массы в технологическом процессе', 'haul_truck_driver', False),
    ('position_002', 'Машинист экскаватора', 'excavator_operator', False),
    ('position_003', 'Водитель автомобиля грузового', None, True),
    ('position_004', 'Машинист бульдозера', 'bulldozer_operator', False),
    ('position_005', 'Слесарь-ремонтник', None, False),
    ('position_006', 'Электрогазосварщик', None, False),
    ('position_007', 'Водитель легкового автомобиля', 'light_vehicle_driver', False),
    ('position_008', 'Водитель погрузчика', 'loader_operator', False),
    ('position_009', 'Помощник машиниста экскаватора', 'assistant_excavator_operator', False),
    ('position_010', 'Ведущий специалист', None, False),
    ('position_011', 'Машинист автогрейдера', 'grader_operator', False),
    ('position_012', 'Горный диспетчер', None, False),
    ('position_013', 'Горный мастер', None, False),
    ('position_014', 'Диспетчер по горно-транспортному оборудованию', None, False),
    ('position_015', 'Начальник участка', None, False),
    ('position_016', 'Кладовщик', None, False),
    ('position_017', 'Слесарь-электрик по ремонту электрооборудования (Автоэлектрик)', None, False),
    ('position_018', 'Специалист', None, False),
    ('position_019', 'Ведущий инженер по охране окружающей среды', None, False),
    ('position_020', 'Делопроизводитель', None, False),
    ('position_021', 'Механик по выпуску и ремонту горно-транспортного оборудования', None, False),
    ('position_022', 'Механик по ремонту вспомогательной техники', None, False),
    ('position_023', 'Механик по ремонту технологических самосвалов', None, False),
    ('position_024', 'Механик по ремонту экскаваторов', None, False),
    ('position_025', 'Механик по техническому обслуживанию', None, False),
    ('position_026', 'Подсобный рабочий', None, False),
    ('position_027', 'Старший механик', None, False),
    ('position_028', 'Техник по учету', None, False),
    ('position_029', 'Ведущий инженер по БДД', None, False),
    ('position_030', 'Ведущий специалист по промышленной безопасности и охране труда', None, False),
    ('position_031', 'Грузчик-стропальщик', None, False),
    ('position_032', 'Заместитель начальника участка', None, False),
    ('position_033', 'Инженер по ТОиР', None, False),
    ('position_034', 'Инженер по шинам', None, False),
    ('position_035', 'Машинист катка', 'roller_operator', False),
    ('position_036', 'Машинист крана автомобильного', 'mobile_crane_operator', False),
    ('position_037', 'Начальник АЗС', None, False),
    ('position_038', 'Начальник отдела', None, False),
    ('position_039', 'Начальник склада', None, False),
    ('position_040', 'Старший горный мастер', None, False),
    ('position_041', 'Техник-наладчик по АСУ ГТК', None, False),
)


def _equipment_type_for_names(EquipmentType, names):
    if not names:
        return None
    for name in names:
        equipment_type = EquipmentType.objects.filter(name__iexact=name).first()
        if equipment_type:
            return equipment_type
    return None


def seed_personnel_catalogue(apps, schema_editor):
    Employee = apps.get_model('users', 'Employee')
    Role = apps.get_model('users', 'Role')
    EquipmentType = apps.get_model('references', 'EquipmentType')
    ProductionSpecialization = apps.get_model('users', 'ProductionSpecialization')
    PersonnelPosition = apps.get_model('users', 'PersonnelPosition')

    specialization_by_code = {}
    for code, name, equipment_type_names, access_role_code in SPECIALIZATIONS:
        access_role = Role.objects.filter(code=access_role_code).first() if access_role_code else None
        specialization, _ = ProductionSpecialization.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'equipment_type': _equipment_type_for_names(EquipmentType, equipment_type_names),
                'access_role': access_role,
                'is_active': True,
            },
        )
        specialization_by_code[code] = specialization

    generic_cargo_specializations = [
        specialization_by_code[code]
        for code in (
            'cargo_kdm_driver',
            'cargo_prm_driver',
            'fuel_truck_driver',
            'watch_bus_driver',
            'mobile_canteen_driver',
        )
    ]
    positions_by_name = {}
    for code, name, default_specialization_code, requires_specialization in POSITIONS:
        position, _ = PersonnelPosition.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'requires_specialization': requires_specialization,
                'default_specialization': specialization_by_code.get(default_specialization_code),
                'is_active': True,
            },
        )
        if name == 'Водитель автомобиля грузового':
            position.allowed_specializations.set(generic_cargo_specializations)
        elif default_specialization_code:
            position.allowed_specializations.set([specialization_by_code[default_specialization_code]])
        else:
            position.allowed_specializations.clear()
        positions_by_name[name] = position

    for position_name, position in positions_by_name.items():
        updates = {'personnel_position': position}
        if position.default_specialization_id:
            updates['base_specialization'] = position.default_specialization
        Employee.objects.filter(position=position_name).update(**updates)


def unseed_personnel_catalogue(apps, schema_editor):
    # Historical employee rows are intentionally retained on rollback.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_assign_truck_fuel_limits'),
        ('shifts', '0011_employeeshift_workplace_code'),
        ('users', '0011_adminactionlog_reversal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, unique=True, verbose_name='Код должности')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Кадровая должность')),
                ('requires_specialization', models.BooleanField(default=False, verbose_name='Требует производственную специализацию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Кадровая должность',
                'verbose_name_plural': 'Кадровые должности',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='personnel_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.personnelposition', verbose_name='Кадровая должность'),
        ),
        migrations.CreateModel(
            name='ProductionSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код специализации')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Производственная специализация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('access_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_specializations', to='users.role', verbose_name='Роль приложения')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_specializations', to='references.equipmenttype', verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Производственная специализация',
                'verbose_name_plural': 'Производственные специализации',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='personnelposition',
            name='allowed_specializations',
            field=models.ManyToManyField(blank=True, related_name='personnel_positions', to='users.productionspecialization', verbose_name='Разрешенные производственные специализации'),
        ),
        migrations.AddField(
            model_name='personnelposition',
            name='default_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_personnel_positions', to='users.productionspecialization', verbose_name='Специализация по умолчанию'),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_employees', to='users.productionspecialization', verbose_name='Базовая производственная специализация'),
        ),
        migrations.CreateModel(
            name='TemporaryWorkTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(verbose_name='Действует по')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен'), ('expired', 'Завершен по окончании вахты')], db_index=True, default='requested', max_length=16, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина запроса')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий ОУП')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошен')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрен')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_work_transfers', to='users.employee', verbose_name='Сотрудник')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_temporary_work_transfers', to='users.employee', verbose_name='Кто запросил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_temporary_work_transfers', to='users.employee', verbose_name='Кто рассмотрел')),
                ('source_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_temporary_transfers', to='users.productionspecialization', verbose_name='Исходная специализация')),
                ('target_specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_temporary_transfers', to='users.productionspecialization', verbose_name='Целевая специализация')),
                ('watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_work_transfers', to='shifts.watchperiod', verbose_name='Вахта')),
            ],
            options={
                'verbose_name': 'Временный производственный перевод',
                'verbose_name_plural': 'Временные производственные переводы',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='tmp_transfer_emp_status_idx'), models.Index(fields=['status', 'effective_to'], name='temp_transfer_status_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__gte', models.F('effective_from'))), name='temp_transfer_dates_valid')],
            },
        ),
        migrations.RunPython(seed_personnel_catalogue, unseed_personnel_catalogue),
    ]
