# Generated by Django 6.0.6 on 2026-07-17 20:15

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


DEPARTMENTS = (
    ('department_001', 'Горный участок №2'),
    ('department_002', 'Ремонтно-механическая служба'),
    ('department_003', 'Сварочный участок'),
    ('department_004', 'Диспетчерская служба'),
    ('department_005', 'Склад №2'),
    ('department_006', 'Отдел промышленной безопасности и охраны труда'),
    ('department_007', 'Административный отдел'),
    ('department_008', 'Отдел безопасности'),
    ('department_009', 'Отдел информационных технологий'),
    ('department_010', 'Отдел охраны окружающей среды'),
    ('department_011', 'Участок №2'),
    ('department_012', 'Отдел проверки контрагентов и контроля за движением ТМЦ'),
    ('department_013', 'Отдел управления персоналом'),
)


WORK_SCHEDULES = (
    (
        'schedule_12',
        'График сменности №12 (2-х сменный, 4-х бригадный)(30 дней, 30 ночей)',
        4,
    ),
    ('schedule_11', 'График №11 (1 сменный, 2-х бригадный) (вахта 30 дней)', 2),
    ('schedule_16', 'График №16 (1 сменный, 2-х бригадный) (вахта 15 дней)', 2),
    (
        'schedule_15',
        'График №15 (1 сменный, 2-х бригадный) (вахта 15 дней) неполное рабочее время',
        2,
    ),
    (
        'schedule_14',
        'График №14 (1 сменный, 2-х бригадный) (вахта 30 дней) неполное рабочее время',
        2,
    ),
    ('schedule_4', 'График №4 (1 сменный 2-х бригадный) 14 дней', 2),
)


def _normalized(value):
    return re.sub(r'\s+', ' ', (value or '').strip()).casefold()


def seed_personnel_structure(apps, schema_editor):
    Employee = apps.get_model('users', 'Employee')
    PersonnelDepartment = apps.get_model('users', 'PersonnelDepartment')
    WorkSchedule = apps.get_model('users', 'WorkSchedule')

    departments_by_name = {}
    for code, name in DEPARTMENTS:
        department, _created = PersonnelDepartment.objects.update_or_create(
            code=code,
            defaults={'name': name, 'is_active': True},
        )
        departments_by_name[_normalized(name)] = department

    schedules_by_name = {}
    for code, name, brigade_count in WORK_SCHEDULES:
        schedule, _created = WorkSchedule.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'brigade_count': brigade_count,
                'is_active': True,
            },
        )
        schedules_by_name[_normalized(name)] = schedule

    schedule_pattern = re.compile(r'^(?P<name>.+?)\s+бригада\s*№?\s*(?P<brigade>[1-4])$', re.IGNORECASE)
    for employee in Employee.objects.all().iterator():
        update_fields = []
        department = departments_by_name.get(_normalized(employee.department))
        if department:
            employee.personnel_department_id = department.id
            update_fields.append('personnel_department')

        schedule_match = schedule_pattern.match(re.sub(r'\s+', ' ', (employee.rotation or '').strip()))
        if schedule_match:
            schedule = schedules_by_name.get(_normalized(schedule_match.group('name')))
            brigade_number = int(schedule_match.group('brigade'))
            if schedule and brigade_number <= schedule.brigade_count:
                employee.work_schedule_id = schedule.id
                employee.brigade_number = brigade_number
                update_fields.extend(['work_schedule', 'brigade_number'])

        if update_fields:
            employee.save(update_fields=update_fields)


def unseed_personnel_structure(apps, schema_editor):
    # Legacy text stays on Employee, so schema rollback does not lose source values.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_personnel_positions_and_temporary_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код подразделения')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Подразделение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='brigade_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Бригада №1'), (2, 'Бригада №2'), (3, 'Бригада №3'), (4, 'Бригада №4')], null=True, verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personnel_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.personneldepartment', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код графика')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='График работы')),
                ('brigade_count', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Количество бригад')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('brigade_count__gte', 1), ('brigade_count__lte', 4)), name='work_schedule_brigade_count_1_4')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.workschedule', verbose_name='График работы'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('brigade_number__isnull', True), models.Q(('brigade_number__gte', 1), ('brigade_number__lte', 4)), _connector='OR'), name='employee_brigade_number_1_4'),
        ),
        migrations.RunPython(seed_personnel_structure, unseed_personnel_structure),
    ]
