# Generated by Django 6.0.6 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_seed_rotation_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код состава вахты')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Утверждённый состав вахты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Утверждённый состав вахты',
                'verbose_name_plural': 'Утверждённые составы вахт',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='watch_composition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employees',
                to='users.watchcomposition',
                verbose_name='Утверждённый состав вахты',
            ),
        ),
    ]
