# Generated by Django 6.0.6 on 2026-08-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_activeapplicationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='Текст')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Куда открыть')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='Метка замены')),
                ('kind', models.CharField(blank=True, max_length=64, verbose_name='Событие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('shown_at', models.DateTimeField(blank=True, null=True, verbose_name='Показано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Push-уведомление',
                'verbose_name_plural': 'Push-уведомления',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['employee', 'shown_at'], name='users_pushn_employe_ce2cf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Адрес подписки')),
                ('p256dh', models.CharField(blank=True, max_length=200, verbose_name='Ключ устройства')),
                ('auth', models.CharField(blank=True, max_length=100, verbose_name='Секрет устройства')),
                ('role_code', models.CharField(blank=True, max_length=64, verbose_name='Роль')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Устройство')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='Неудач подряд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя доставка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='users_webpu_employe_ff928d_idx')],
            },
        ),
    ]
