# Generated by Django 6.0.6 on 2026-08-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pushnotification_webpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Роль')),
                ('app_version', models.CharField(blank=True, max_length=64, verbose_name='Версия приложения')),
                ('screen', models.CharField(blank=True, max_length=120, verbose_name='Экран')),
                ('message', models.CharField(max_length=500, verbose_name='Ошибка')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Файл')),
                ('stack', models.TextField(blank=True, verbose_name='Стек')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Телефон и браузер')),
                ('happened_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_errors', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ошибка на телефоне',
                'verbose_name_plural': 'Ошибки на телефонах',
                'ordering': ['-happened_at'],
            },
        ),
    ]
