# Generated by Django 6.0.6 on 2026-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_client_error_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_protected',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Защищённая карточка'),
        ),
    ]
