# Generated by Django 6.0.6 on 2026-09-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_activeapplicationsession_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contractor_access_from',
            field=models.DateField(blank=True, null=True, verbose_name='Допуск действует с'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contractor_access_until',
            field=models.DateField(blank=True, null=True, verbose_name='Допуск действует по'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('staff', 'Штатный сотрудник'), ('contractor', 'Сотрудник подрядчика')], default='staff', max_length=16, verbose_name='Тип сотрудника'),
        ),
        migrations.CreateModel(
            name='ContractorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование организации')),
                ('short_name', models.CharField(blank=True, max_length=128, verbose_name='Краткое наименование')),
                ('contract_number', models.CharField(blank=True, max_length=128, verbose_name='Номер договора')),
                ('contract_valid_from', models.DateField(blank=True, null=True, verbose_name='Договор действует с')),
                ('contract_valid_until', models.DateField(blank=True, null=True, verbose_name='Договор действует по')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон подрядчика')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Допущен к работам')),
            ],
            options={
                'verbose_name': 'Организация-подрядчик',
                'verbose_name_plural': 'Организации-подрядчики',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('contract_valid_from__isnull', True), ('contract_valid_until__isnull', True), ('contract_valid_until__gte', models.F('contract_valid_from')), _connector='OR'), name='contractor_org_contract_dates_ordered')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='contractor_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.contractororganization', verbose_name='Организация-подрядчик'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_access_from__isnull', True), ('contractor_access_until__isnull', True), ('contractor_access_until__gte', models.F('contractor_access_from')), _connector='OR'), name='employee_contractor_access_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contractor_access_from__isnull', True), ('contractor_access_until__isnull', True), ('contractor_organization__isnull', True), ('employment_type', 'staff')), models.Q(('contractor_access_from__isnull', False), ('contractor_access_until__isnull', False), ('contractor_organization__isnull', False), ('employment_type', 'contractor')), _connector='OR'), name='employee_contractor_fields_match_type'),
        ),
    ]
