# Generated by Django 6.0.6 on 2026-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_employee_contractor_access_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccess',
            name='driver_quick_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='Причины простоя в барабане водителя'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='driver_quick_reasons_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Барабан настроен'),
        ),
    ]
