# Generated by Django 6.0.6 on 2026-09-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_employeeaccess_driver_quick_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativePushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('rustore', 'RuStore Push')], default='fcm', max_length=16, verbose_name='Провайдер')),
                ('token', models.CharField(max_length=4096, verbose_name='Токен устройства')),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=16, verbose_name='Платформа')),
                ('app_id', models.CharField(max_length=160, verbose_name='Идентификатор приложения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='Неудач подряд')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя доставка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_push_devices', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Нативное push-устройство',
                'verbose_name_plural': 'Нативные push-устройства',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='nativepush_emp_active_idx'), models.Index(fields=['provider', 'is_active'], name='nativepush_prov_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'token'), name='nativepush_provider_token_uniq')],
            },
        ),
    ]
