from django.urls import path

from .views import (
    arrival_roster_confirm_unambiguous_view,
    arrival_roster_approval_confirm_view,
    arrival_roster_create_revision_view,
    arrival_roster_dates_view,
    arrival_roster_employee_add_view,
    arrival_roster_external_add_view,
    arrival_roster_index_view,
    arrival_roster_issue_reopen_view,
    arrival_roster_issue_resolve_view,
    arrival_roster_notes_view,
    arrival_roster_participation_view,
    arrival_roster_pool_create_view,
    arrival_roster_routing_view,
    arrival_roster_review_view,
    arrival_roster_resident_clear_view,
    arrival_roster_resident_search_view,
    arrival_roster_resident_select_view,
    arrival_roster_upload_form_view,
    arrival_roster_upload_view,
    cycle_action_view,
    cycle_create_view,
    cycle_document_packet_view,
    cycle_export_view,
    documentation_complete_view,
    employee_home_view,
    employee_response_view,
    site_manager_decision_view,
    site_manager_manifest_view,
    site_manager_queue_view,
    site_manager_service_worker_view,
    timekeeper_cycle_view,
    timekeeper_brigade_phase_calendar_confirm_view,
    timekeeper_brigade_phase_calendar_create_view,
    timekeeper_brigade_phase_calendar_view,
    timekeeper_dashboard_view,
    timekeeper_manifest_view,
    timekeeper_response_edit_view,
    timekeeper_service_worker_view,
)


urlpatterns = [
    path('timekeeper/', timekeeper_dashboard_view, name='rotation_timekeeper_dashboard'),
    path(
        'timekeeper/brigade-phase-calendar/',
        timekeeper_brigade_phase_calendar_view,
        name='timekeeper_brigade_phase_calendar',
    ),
    path(
        'timekeeper/brigade-phase-calendar/create/',
        timekeeper_brigade_phase_calendar_create_view,
        name='timekeeper_brigade_phase_calendar_create',
    ),
    path(
        'timekeeper/brigade-phase-calendar/<int:version_id>/confirm/',
        timekeeper_brigade_phase_calendar_confirm_view,
        name='timekeeper_brigade_phase_calendar_confirm',
    ),
    path(
        'timekeeper/arrival-rosters/',
        arrival_roster_index_view,
        name='arrival_roster_index',
    ),
    path(
        'timekeeper/arrival-rosters/from-employees/',
        arrival_roster_pool_create_view,
        name='arrival_roster_pool_create',
    ),
    path(
        'timekeeper/arrival-rosters/new/',
        arrival_roster_upload_form_view,
        name='arrival_roster_upload_form',
    ),
    path(
        'timekeeper/arrival-rosters/upload/',
        arrival_roster_upload_view,
        name='arrival_roster_upload',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/',
        arrival_roster_review_view,
        name='arrival_roster_review',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/employees/add/',
        arrival_roster_employee_add_view,
        name='arrival_roster_employee_add',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/external/add/',
        arrival_roster_external_add_view,
        name='arrival_roster_external_add',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/confirm-unambiguous/',
        arrival_roster_confirm_unambiguous_view,
        name='arrival_roster_confirm_unambiguous',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/approve/',
        arrival_roster_approval_confirm_view,
        name='arrival_roster_approval_confirm',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/routing/',
        arrival_roster_routing_view,
        name='arrival_roster_routing',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/create-revision/',
        arrival_roster_create_revision_view,
        name='arrival_roster_create_revision',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/residents/search/',
        arrival_roster_resident_search_view,
        name='arrival_roster_resident_search',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/resident/select/',
        arrival_roster_resident_select_view,
        name='arrival_roster_resident_select',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/resident/clear/',
        arrival_roster_resident_clear_view,
        name='arrival_roster_resident_clear',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/participation/',
        arrival_roster_participation_view,
        name='arrival_roster_participation',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/dates/',
        arrival_roster_dates_view,
        name='arrival_roster_dates',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/rows/<int:match_id>/notes/',
        arrival_roster_notes_view,
        name='arrival_roster_notes',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/issues/<int:issue_id>/resolve/',
        arrival_roster_issue_resolve_view,
        name='arrival_roster_issue_resolve',
    ),
    path(
        'timekeeper/arrival-rosters/<int:version_id>/issues/<int:issue_id>/reopen/',
        arrival_roster_issue_reopen_view,
        name='arrival_roster_issue_reopen',
    ),
    path('timekeeper/campaigns/new/', cycle_create_view, name='rotation_cycle_create'),
    path('timekeeper/campaigns/<int:cycle_id>/', timekeeper_cycle_view, name='rotation_timekeeper_cycle'),
    path('timekeeper/campaigns/<int:cycle_id>/<str:action>/', cycle_action_view, name='rotation_cycle_action'),
    path('timekeeper/campaigns/<int:cycle_id>/export.xlsx', cycle_export_view, name='rotation_cycle_export'),
    path(
        'timekeeper/campaigns/<int:cycle_id>/extension-data.docx',
        cycle_document_packet_view,
        name='rotation_cycle_document_packet',
    ),
    path(
        'timekeeper/campaigns/<int:cycle_id>/responses/<int:response_id>/',
        timekeeper_response_edit_view,
        name='rotation_timekeeper_response_edit',
    ),
    path(
        'timekeeper/extensions/<int:case_id>/complete/',
        documentation_complete_view,
        name='rotation_documentation_complete',
    ),
    path('my/rotation/', employee_home_view, name='rotation_employee_home'),
    path('my/rotation/<int:response_id>/', employee_response_view, name='rotation_employee_response'),
    path('site-manager/extensions/', site_manager_queue_view, name='rotation_site_manager_queue'),
    path(
        'site-manager/extensions/<int:case_id>/<str:decision>/',
        site_manager_decision_view,
        name='rotation_site_manager_decision',
    ),
    path('timekeeper.webmanifest', timekeeper_manifest_view, name='timekeeper_manifest'),
    path('timekeeper-sw.js', timekeeper_service_worker_view, name='timekeeper_service_worker'),
    path('site-manager.webmanifest', site_manager_manifest_view, name='site_manager_manifest'),
    path('site-manager-sw.js', site_manager_service_worker_view, name='site_manager_service_worker'),
]
