DEFAULT_EQUIPMENT_STATES = [
    {
        'code': 'inactive',
        'name': 'Неактивна',
        'short_label': 'Неактивна',
        'color_group': 'gray',
        'semantic_group': 'terminal',
        'priority': 10,
        'blocks_operation': True,
        'is_terminal': True,
        'description': 'Техника не участвует в текущей производственной работе.',
    },
    {
        'code': 'garage',
        'name': 'В гараже',
        'short_label': 'Гараж',
        'color_group': 'gray',
        'semantic_group': 'availability',
        'priority': 20,
        'allows_assignment': True,
        'allows_drag': True,
        'description': 'Техника находится вне активного комплекса и может быть назначена.',
    },
    {
        'code': 'free',
        'name': 'Свободен',
        'short_label': 'Свободен',
        'color_group': 'yellow',
        'semantic_group': 'availability',
        'priority': 30,
        'allows_assignment': True,
        'allows_drag': True,
        'requires_attention': True,
        'description': 'Техника доступна или ожидает назначения. В проекте желтый цвет означает ожидание действия, а не аварию.',
    },
    {
        'code': 'assigned',
        'name': 'Назначена',
        'short_label': 'Назначена',
        'color_group': 'blue',
        'semantic_group': 'assignment',
        'priority': 40,
        'allows_drag': True,
        'description': 'Техника закреплена за комплексом или задачей, но еще не выполняет активную операцию.',
    },
    {
        'code': 'working',
        'name': 'В работе',
        'short_label': 'В работе',
        'color_group': 'green',
        'semantic_group': 'operation',
        'priority': 50,
        'description': 'Техника выполняет полезную производственную операцию.',
    },
    {
        'code': 'loading',
        'name': 'Погрузка',
        'short_label': 'Погрузка',
        'color_group': 'green',
        'semantic_group': 'operation',
        'priority': 55,
        'description': 'Самосвал находится под погрузкой или операция погрузки активна.',
    },
    {
        'code': 'loaded_waiting_unload',
        'name': 'На разгрузку',
        'short_label': 'На разгрузку',
        'color_group': 'green',
        'semantic_group': 'operation',
        'priority': 65,
        'blocks_operation': True,
        'description': 'Самосвал загружен экскаватором и едет к точке разгрузки. Это серверное состояние после отправки рейса.',
    },
    {
        'code': 'waiting',
        'name': 'Ожидает',
        'short_label': 'Ожидает',
        'color_group': 'yellow',
        'semantic_group': 'availability',
        'priority': 70,
        'requires_attention': True,
        'description': 'Техника ожидает решения, подтверждения, разгрузки или следующего действия.',
    },
    {
        'code': 'sync_pending',
        'name': 'Ожидание синхронизации',
        'short_label': 'Синхронизация',
        'color_group': 'yellow',
        'semantic_group': 'system',
        'priority': 80,
        'requires_attention': True,
        'description': 'Локальное действие еще не подтверждено сервером. Это системная подсветка, а не техническое состояние машины.',
    },
    {
        'code': 'maintenance',
        'name': 'Техническое обслуживание',
        'short_label': 'ТО',
        'color_group': 'orange',
        'semantic_group': 'technical',
        'priority': 90,
        'blocks_operation': True,
        'requires_reason': True,
        'description': 'Плановое обслуживание или сервисная операция механической службы.',
    },
    {
        'code': 'repair',
        'name': 'Ремонт',
        'short_label': 'Ремонт',
        'color_group': 'orange',
        'semantic_group': 'technical',
        'priority': 100,
        'blocks_operation': True,
        'requires_attention': True,
        'requires_reason': True,
        'description': 'Техника передана в ремонт. Детализация ремонта относится к механической службе.',
    },
    {
        'code': 'downtime',
        'name': 'Простой',
        'short_label': 'Простой',
        'color_group': 'red',
        'semantic_group': 'technical',
        'priority': 110,
        'blocks_operation': True,
        'requires_attention': True,
        'requires_reason': True,
        'description': 'Техника не может работать из-за простоя, причины или внешнего ограничения.',
    },
    {
        'code': 'breakdown',
        'name': 'Поломка',
        'short_label': 'Поломка',
        'color_group': 'red',
        'semantic_group': 'technical',
        'priority': 120,
        'blocks_operation': True,
        'requires_attention': True,
        'requires_reason': True,
        'description': 'Критическая техническая проблема. Требуется реакция механиков или диспетчера.',
    },
    {
        'code': 'conflict',
        'name': 'Конфликт данных',
        'short_label': 'Конфликт',
        'color_group': 'red',
        'semantic_group': 'system',
        'priority': 130,
        'blocks_operation': True,
        'requires_attention': True,
        'description': 'Система обнаружила противоречие: двойное назначение, конфликт смены или ошибочное состояние.',
    },
]


def upsert_default_equipment_states():
    from .models import EquipmentState

    EquipmentState.objects.filter(code='in_transit').delete()

    for state in DEFAULT_EQUIPMENT_STATES:
        EquipmentState.objects.update_or_create(
            code=state['code'],
            defaults={
                'name': state['name'],
                'short_label': state.get('short_label', ''),
                'color_group': state['color_group'],
                'semantic_group': state['semantic_group'],
                'priority': state.get('priority', 100),
                'allows_assignment': state.get('allows_assignment', False),
                'allows_drag': state.get('allows_drag', False),
                'blocks_operation': state.get('blocks_operation', False),
                'requires_attention': state.get('requires_attention', False),
                'requires_reason': state.get('requires_reason', False),
                'is_terminal': state.get('is_terminal', False),
                'is_active': state.get('is_active', True),
                'description': state.get('description', ''),
            },
        )
    return len(DEFAULT_EQUIPMENT_STATES)
