# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('shifts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем, м3')),
                ('tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тоннаж')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнен')),
                ('is_carryover', models.BooleanField(default=False, verbose_name='Переходящий рейс')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to='users.employee', verbose_name='Водитель')),
                ('dump_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.dumppoint', verbose_name='Точка разгрузки')),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excavator_trips', to='references.equipment', verbose_name='Экскаватор')),
                ('excavator_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excavator_trips', to='users.employee', verbose_name='Машинист экскаватора')),
                ('loading_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loaded_trips', to='shifts.employeeshift', verbose_name='Смена загрузки')),
                ('rock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.rocktype', verbose_name='Порода')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_trips', to='references.equipment', verbose_name='Самосвал')),
                ('unloading_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unloaded_trips', to='shifts.employeeshift', verbose_name='Смена разгрузки')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
