# Generated by Django 6.0.6 on 2026-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='downtime_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Простои'),
        ),
        migrations.AddField(
            model_name='trip',
            name='loading_block',
            field=models.CharField(blank=True, max_length=64, verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='trip',
            name='loading_horizon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Горизонт погрузки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Плановое задание, м3'),
        ),
        migrations.AddField(
            model_name='trip',
            name='transport_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Плечо транспортировки, км'),
        ),
    ]
