# Generated by Django 6.0.6 on 2026-06-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('shifts', '0002_employeeshift_end_engine_hours_and_more'),
        ('trips', '0002_trip_downtime_text_trip_loading_block_and_more'),
        ('users', '0002_driverprimaryregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('service_close_shift', 'Служебное закрытие смены'), ('cancel_assignment', 'Снятие назначения'), ('cancel_trip', 'Отмена рейса'), ('complete_trip', 'Служебное завершение рейса')], max_length=64, verbose_name='Тип действия')),
                ('target_summary', models.CharField(max_length=255, verbose_name='Краткое описание объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда выполнено')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_action_logs', to='users.employee', verbose_name='Кто выполнил действие')),
                ('haul_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_action_logs', to='assignments.haulassignment', verbose_name='Назначение')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_action_logs', to='shifts.employeeshift', verbose_name='Смена')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_action_logs', to='trips.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Диспетчерское действие',
                'verbose_name_plural': 'Диспетчерские действия',
                'ordering': ['-created_at'],
            },
        ),
    ]
