# Generated by Django 6.0.6 on 2026-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_dispatcheractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcheractionlog',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина действия'),
        ),
    ]
