# Generated by Django 6.0.6 on 2026-07-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_equipmentstate'),
        ('trips', '0005_truck_loaded_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_dump_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_trips', to='references.dumppoint', verbose_name='Фактическая точка разгрузки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='assigned_dump_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trips', to='references.dumppoint', verbose_name='Назначенная точка разгрузки'),
        ),
    ]
