# Generated by Django 6.0.6 on 2026-07-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_actual_dump_point_trip_assigned_dump_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('loaded_waiting_unload', 'На разгрузку'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='active', max_length=32, verbose_name='Статус'),
        ),
    ]
