# Generated by Django 6.0.6 on 2026-08-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_update_downtime_reason_state_semantics'),
        ('references', '0007_assign_truck_fuel_limits'),
        ('shifts', '0015_brigade_phase_actor_accesses'),
        ('trips', '0008_trip_cancelled_at'),
        ('users', '0018_employee_watch_profile_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(choices=[('trip_count', 'Количество рейсов'), ('transported_volume_m3', 'Перевезённый объём, м3'), ('transported_tonnage', 'Перевезённый тоннаж'), ('downtime_minutes', 'Минуты простоя'), ('productive_time_minutes', 'Минуты производительной работы'), ('paid_downtime_minutes', 'Оплачиваемые минуты простоя'), ('excavator_loaded_volume_m3', 'Объём погрузки экскаватора, м3')], max_length=64, verbose_name='Показатель')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Изменение')),
                ('unit', models.CharField(max_length=24, verbose_name='Единица измерения')),
                ('status', models.CharField(choices=[('pending_review', 'Ожидает проверки'), ('held', 'Приостановлено спором'), ('accepted', 'Принято в расчёт'), ('booked', 'Включено в закрытый расчёт'), ('correction_required', 'Требуется корректировка'), ('corrected', 'Скорректировано'), ('rejected', 'Исключено из расчёта')], default='pending_review', max_length=32, verbose_name='Расчётное состояние')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято в расчёт')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Включено в закрытый расчёт')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='Скорректировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('correction_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='trips.interventionimpact', verbose_name='Корректирует последствие')),
            ],
            options={
                'verbose_name': 'Расчётное последствие вмешательства',
                'verbose_name_plural': 'Расчётные последствия вмешательств',
                'ordering': ['intervention_id', 'metric_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('employee', 'Сотрудник'), ('dispatcher_override', 'Служебное действие диспетчера'), ('telemetry', 'Телеметрия'), ('system', 'Система')], default='dispatcher_override', max_length=32, verbose_name='Источник')),
                ('action_type', models.CharField(choices=[('complete_trip', 'Подтверждение разгрузки'), ('start_downtime', 'Начало простоя'), ('close_downtime', 'Завершение простоя'), ('cancel_trip', 'Отмена рейса'), ('service_close_shift', 'Служебное закрытие смены')], max_length=64, verbose_name='Тип действия')),
                ('reason_code', models.CharField(choices=[('device_failure', 'Неисправность устройства'), ('no_connection', 'Нет связи'), ('employee_unavailable', 'Сотрудник недоступен'), ('operational_correction', 'Оперативная корректировка'), ('other', 'Другая причина')], max_length=64, verbose_name='Код причины')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('occurred_at', models.DateTimeField(verbose_name='Фактическое время события')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('operational_status', models.CharField(choices=[('created', 'Создано'), ('validated', 'Проверено'), ('applied', 'Применено'), ('compensated', 'Скорректировано отдельным событием'), ('rejected', 'Отклонено')], default='applied', max_length=32, verbose_name='Операционное состояние')),
                ('review_status', models.CharField(choices=[('not_required', 'Проверка не требуется'), ('awaiting_delivery', 'Ожидает доставки уведомления'), ('awaiting_objection', 'Ожидает возможного возражения'), ('accepted_silently', 'Принято без возражения'), ('disputed', 'Оспорено'), ('under_review', 'На рассмотрении'), ('upheld', 'Подтверждено руководителем'), ('adjusted', 'Скорректировано'), ('rejected', 'Отклонено')], default='awaiting_delivery', max_length=32, verbose_name='Состояние проверки')),
                ('notification_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Попытка уведомления')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомление доставлено')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Сотрудник ознакомлен')),
                ('objection_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок возражения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Спор разрешён')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='Решение по спору')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='Ключ идемпотентности')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_operational_interventions', to='users.employee', verbose_name='Кто зарегистрировал')),
                ('actor_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_operational_interventions', to='shifts.employeeshift', verbose_name='Смена регистратора')),
                ('compensation_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='trips.operationalintervention', verbose_name='Корректирует вмешательство')),
                ('dispatcher_action_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_intervention', to='trips.dispatcheractionlog', verbose_name='Запись старого журнала диспетчера')),
                ('downtime_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_interventions', to='downtimes.downtimeevent', verbose_name='Событие простоя')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_interventions', to='references.equipment', verbose_name='Техника')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_operational_interventions', to='users.employee', verbose_name='Кто разрешил спор')),
                ('subject_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_interventions', to='users.employee', verbose_name='Кого затрагивает')),
                ('subject_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_interventions', to='shifts.employeeshift', verbose_name='Затронутая смена')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_interventions', to='trips.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Операционное вмешательство',
                'verbose_name_plural': 'Операционные вмешательства',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', models.CharField(choices=[('operational', 'Операционный'), ('review', 'Проверка и спор'), ('calculation', 'Расчётный')], max_length=24, verbose_name='Контур')),
                ('from_status', models.CharField(blank=True, max_length=32, verbose_name='Исходное состояние')),
                ('to_status', models.CharField(max_length=32, verbose_name='Новое состояние')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда выполнено')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_intervention_transitions', to='users.employee', verbose_name='Кто выполнил переход')),
                ('impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_transitions', to='trips.interventionimpact', verbose_name='Расчётное последствие')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_transitions', to='trips.operationalintervention', verbose_name='Вмешательство')),
            ],
            options={
                'verbose_name': 'Переход состояния вмешательства',
                'verbose_name_plural': 'Переходы состояний вмешательств',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterventionReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('notification_attempted', 'Попытка уведомления'), ('delivered', 'Уведомление доставлено'), ('acknowledged', 'Сотрудник ознакомлен'), ('disputed', 'Сотрудник оспорил'), ('review_started', 'Рассмотрение начато'), ('upheld', 'Действие подтверждено'), ('adjusted', 'Действие скорректировано'), ('rejected', 'Действие отклонено'), ('silent_acceptance', 'Срок возражения истёк')], max_length=32, verbose_name='Событие проверки')),
                ('channel', models.CharField(blank=True, max_length=32, verbose_name='Канал')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда выполнено')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_intervention_review_events', to='users.employee', verbose_name='Кто зафиксировал')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='trips.operationalintervention', verbose_name='Вмешательство')),
            ],
            options={
                'verbose_name': 'Событие проверки вмешательства',
                'verbose_name_plural': 'События проверки вмешательств',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interventionimpact',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impacts', to='trips.operationalintervention', verbose_name='Вмешательство'),
        ),
        migrations.AddConstraint(
            model_name='operationalintervention',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('source', 'action_type', 'idempotency_key'), name='unique_operational_intervention_action'),
        ),
        migrations.AddConstraint(
            model_name='operationalintervention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'dispatcher_override'), _negated=True), ('actor__isnull', False), _connector='OR'), name='dispatcher_override_requires_actor'),
        ),
    ]
