# Generated by Django 6.0.6 on 2026-09-07 14:46

from django.db import migrations, models
from django.db.models import Count


def validate_unique_open_trip_per_truck(apps, schema_editor):
    Trip = apps.get_model('trips', 'Trip')
    duplicate = (
        Trip.objects.filter(status__in=['active', 'loaded_waiting_unload'])
        .values('truck_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
        .order_by('truck_id')
        .first()
    )
    if duplicate:
        raise RuntimeError(
            'Нельзя установить ограничение одного открытого рейса: '
            f"у самосвала id={duplicate['truck_id']} найдено открытых рейсов: {duplicate['total']}."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_equipment_contractor_organization'),
        ('shifts', '0015_brigade_phase_actor_accesses'),
        ('trips', '0008_trip_cancelled_at'),
        ('users', '0024_employee_contractor_access_from_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_unique_open_trip_per_truck, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'loaded_waiting_unload'))), fields=('truck',), name='uniq_open_trip_per_truck'),
        ),
    ]
