# Generated by Django 6.0.6 on 2026-09-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_excavatorshiftreadingconfirmation'),
        ('trips', '0009_unique_open_trip_per_truck'),
        ('users', '0024_employee_contractor_access_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='closure_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uncontrolled_trip_closures', to='users.employee', verbose_name='Автор следующей отгрузки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_control_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_trips', to='shifts.employeeshift', verbose_name='Смена водителя, получившая рейс'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_participation_recorded',
            field=models.BooleanField(default=False, verbose_name='Участие водителя зафиксировано при отправке'),
        ),
        migrations.AddField(
            model_name='trip',
            name='operationally_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Снят с оперативного контроля'),
        ),
        migrations.AddField(
            model_name='trip',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_trip', to='trips.trip', verbose_name='Следующая отгрузка — основание снятия с контроля'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unload_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждение разгрузки получено сервером'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unload_time_source',
            field=models.CharField(choices=[('unknown', 'Неизвестно'), ('driver_device', 'Часы устройства водителя'), ('server_receipt', 'Время получения сервером')], default='unknown', max_length=24, verbose_name='Источник времени разгрузки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('loaded_waiting_unload', 'На разгрузку'), ('completed', 'Выполнен'), ('uncontrolled', 'Разгрузка непроконтролированная'), ('cancelled', 'Отменен')], default='active', max_length=32, verbose_name='Статус'),
        ),
    ]
