# Generated by Django 6.0.6 on 2026-08-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_operational_interventions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcheractionlog',
            name='action_type',
            field=models.CharField(choices=[('service_close_shift', 'Служебное закрытие смены'), ('cancel_assignment', 'Снятие назначения'), ('cancel_trip', 'Отмена рейса'), ('complete_trip', 'Служебное завершение рейса'), ('start_downtime', 'Служебное начало простоя'), ('close_downtime', 'Служебное завершение простоя')], max_length=64, verbose_name='Тип действия'),
        ),
    ]
