# Generated by Django 6.0.6 on 2026-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_unique_open_trip_per_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcheractionlog',
            name='action_type',
            field=models.CharField(choices=[('service_close_shift', 'Служебное закрытие смены'), ('cancel_assignment', 'Снятие назначения'), ('cancel_trip', 'Отмена рейса'), ('complete_trip', 'Служебное завершение рейса'), ('manual_trip', 'Ручной рейс диспетчера')], max_length=64, verbose_name='Тип действия'),
        ),
    ]
