# Generated by Django 6.0.6 on 2026-08-25 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_dispatcher_downtime_action_types'),
        ('users', '0018_employee_watch_profile_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalintervention',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_operational_interventions', to='users.employee', verbose_name='Кто подтвердил ознакомление'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='acknowledgement_channel',
            field=models.CharField(blank=True, choices=[('pwa', 'Приложение сотрудника'), ('radio', 'Рация'), ('phone', 'Телефон'), ('in_person', 'Лично'), ('paper', 'Подпись на бумаге'), ('supervisor', 'Через непосредственного руководителя')], max_length=32, verbose_name='Канал ознакомления'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='acknowledgement_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к ознакомлению'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Эскалировано'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'Без эскалации'), ('management', 'Руководство'), ('personnel_accounting', 'ОУП / расчётный контур')], default='none', max_length=32, verbose_name='Уровень эскалации'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='resolution_code',
            field=models.CharField(blank=True, choices=[('uphold', 'Подтвердить исходное действие'), ('adjust', 'Скорректировать расчётные последствия'), ('reject', 'Исключить расчётные последствия')], max_length=24, verbose_name='Код решения'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок рассмотрения'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрение начато'),
        ),
        migrations.AddField(
            model_name='operationalintervention',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewing_operational_interventions', to='users.employee', verbose_name='Ответственный за рассмотрение'),
        ),
        migrations.AlterField(
            model_name='interventionreviewevent',
            name='event_type',
            field=models.CharField(choices=[('notification_attempted', 'Попытка уведомления'), ('delivered', 'Уведомление доставлено'), ('acknowledged', 'Сотрудник ознакомлен'), ('disputed', 'Сотрудник оспорил'), ('review_started', 'Рассмотрение начато'), ('upheld', 'Действие подтверждено'), ('adjusted', 'Действие скорректировано'), ('rejected', 'Действие отклонено'), ('silent_acceptance', 'Срок возражения истёк'), ('escalated', 'Просроченный разбор эскалирован')], max_length=32, verbose_name='Событие проверки'),
        ),
    ]
