# Generated by Django 6.0.6 on 2026-09-14 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_numbered_shift_labels'),
        ('references', '0010_remove_obsolete_cargo_aliases'),
        ('shifts', '0020_shiftclientaction_request_signature'),
        ('trips', '0012_trip_offline_loading_times'),
        ('users', '0024_employee_contractor_access_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBucketAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_acceptance_id', models.CharField(max_length=128, unique=True, verbose_name='Неизменяемый ID временного приёма')),
                ('status', models.CharField(choices=[('accepted', 'Принят под свободный ковш'), ('cancelled', 'Отменён до погрузки'), ('used', 'Погружен'), ('closed', 'Завершён')], default='accepted', max_length=16, verbose_name='Состояние временного приёма')),
                ('occurred_at', models.DateTimeField(verbose_name='Принят на устройстве')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принят сервером')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Погружен')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_bucket_excavator_acceptances', to='references.equipment', verbose_name='Экскаватор')),
                ('loading_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_bucket_acceptances', to='shifts.employeeshift', verbose_name='Смена приёма')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_bucket_acceptances', to='users.employee', verbose_name='Машинист экскаватора')),
                ('primary_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_bucket_acceptances', to='assignments.haulassignment', verbose_name='Основное закрепление при приёме')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_bucket_truck_acceptances', to='references.equipment', verbose_name='Самосвал')),
                ('used_trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='free_bucket_acceptance', to='trips.trip', verbose_name='Рейс свободного ковша')),
            ],
            options={
                'verbose_name': 'Приём под свободный ковш',
                'verbose_name_plural': 'Приёмы под свободный ковш',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['excavator', 'status'], name='free_bucket_exc_status'), models.Index(fields=['truck', 'status'], name='free_bucket_truck_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['accepted', 'used'])), fields=('truck',), name='unique_open_free_bucket_acceptance_per_truck')],
            },
        ),
    ]
