# Generated by Django 6.0.6 on 2026-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_numbered_shift_labels'),
        ('references', '0010_remove_obsolete_cargo_aliases'),
        ('shifts', '0020_shiftclientaction_request_signature'),
        ('trips', '0016_trip_driver_device_load_time'),
        ('users', '0026_native_push_device'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='freebucketacceptance',
            name='free_bucket_accept_fields_consistent',
        ),
        migrations.RemoveConstraint(
            model_name='freebucketacceptance',
            name='free_bucket_status_fields_consistent',
        ),
        migrations.AddField(
            model_name='freebucketacceptance',
            name='accepted_by_driver_action',
            field=models.BooleanField(default=False, verbose_name='Принят отметкой водителя'),
        ),
        migrations.AddConstraint(
            model_name='freebucketacceptance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('loading_shift__isnull', True), ('operator__isnull', True)), models.Q(('accepted_at__isnull', False), ('loading_shift__isnull', False), ('operator__isnull', False)), models.Q(('accepted_at__isnull', False), ('accepted_by_driver_action', True), ('loading_shift__isnull', True), ('operator__isnull', True), ('requested_by__isnull', False)), _connector='OR'), name='free_bucket_accept_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='freebucketacceptance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_by_driver_action', False), ('cancelled_at__isnull', True), ('closed_at__isnull', True), ('operator__isnull', True), ('requested_by__isnull', False), ('status', 'requested'), ('used_at__isnull', True), ('used_trip__isnull', True)), models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', True), ('status', 'accepted'), ('used_at__isnull', True), ('used_trip__isnull', True), models.Q(('operator__isnull', False), models.Q(('accepted_at__isnull', False), ('accepted_by_driver_action', True), ('requested_by__isnull', False)), _connector='OR')), models.Q(('cancelled_at__isnull', False), ('closed_at__isnull', True), ('requested_by__isnull', False), ('status', 'cancelled'), ('used_at__isnull', True), ('used_trip__isnull', True)), models.Q(('cancelled_at__isnull', False), ('closed_at__isnull', True), ('operator__isnull', False), ('status', 'cancelled'), ('used_at__isnull', True), ('used_trip__isnull', True)), models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', True), ('status', 'used'), ('used_at__isnull', False), ('used_trip__isnull', False), models.Q(('operator__isnull', False), models.Q(('accepted_at__isnull', False), ('accepted_by_driver_action', True), ('requested_by__isnull', False)), _connector='OR')), models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', False), ('status', 'closed'), ('used_at__isnull', False), ('used_trip__isnull', False), models.Q(('operator__isnull', False), models.Q(('accepted_at__isnull', False), ('accepted_by_driver_action', True), ('requested_by__isnull', False)), _connector='OR')), _connector='OR'), name='free_bucket_status_fields_consistent'),
        ),
    ]
