# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Номер общежития')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежития',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DumpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Точка разгрузки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Точка разгрузки',
                'verbose_name_plural': 'Точки разгрузки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Вид техники')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид техники',
                'verbose_name_plural': 'Виды техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Порода/груз')),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Плотность')),
                ('loosening_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Коэффициент разрыхления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Блок')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='references.dormitory', verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Блок общежития',
                'verbose_name_plural': 'Блоки общежитий',
                'ordering': ['dormitory__number', 'name'],
                'unique_together': {('dormitory', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Модель')),
                ('payload_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Грузоподъемность, т')),
                ('body_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем кузова/ковша, м3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipmenttype', verbose_name='Вид техники')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
                'ordering': ['equipment_type__name', 'name'],
                'unique_together': {('equipment_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_number', models.CharField(max_length=64, unique=True, verbose_name='Гаражный номер')),
                ('vin', models.CharField(blank=True, max_length=128, verbose_name='VIN/серийный номер')),
                ('is_own', models.BooleanField(default=True, verbose_name='Своя техника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.equipmentmodel', verbose_name='Модель')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipmenttype', verbose_name='Вид техники')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['equipment_type__name', 'garage_number'],
            },
        ),
        migrations.CreateModel(
            name='DormitorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Секция')),
                ('day_capacity', models.PositiveIntegerField(default=3, verbose_name='Мест для дневной смены')),
                ('night_capacity', models.PositiveIntegerField(default=3, verbose_name='Мест для ночной смены')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='references.dormitoryblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Секция общежития',
                'verbose_name_plural': 'Секции общежитий',
                'ordering': ['block__dormitory__number', 'block__name', 'name'],
                'unique_together': {('block', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TruckCapacityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кубатура рейса, м3')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.equipmentmodel', verbose_name='Модель самосвала')),
                ('rock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.rocktype', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Правило кубатуры самосвала',
                'verbose_name_plural': 'Правила кубатуры самосвалов',
                'unique_together': {('equipment_model', 'rock_type')},
            },
        ),
    ]
