# Generated by Django 6.0.6 on 2026-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код состояния')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('short_label', models.CharField(blank=True, max_length=64, verbose_name='Короткая подпись')),
                ('color_group', models.CharField(choices=[('gray', 'Серый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('red', 'Красный')], max_length=16, verbose_name='Цветовая группа')),
                ('semantic_group', models.CharField(choices=[('availability', 'Доступность'), ('assignment', 'Назначение'), ('operation', 'Рабочая операция'), ('technical', 'Техническое состояние'), ('system', 'Системное состояние'), ('terminal', 'Выведено из работы')], max_length=32, verbose_name='Смысловая группа')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет отображения')),
                ('allows_assignment', models.BooleanField(default=False, verbose_name='Можно назначать')),
                ('allows_drag', models.BooleanField(default=False, verbose_name='Можно перетаскивать')),
                ('blocks_operation', models.BooleanField(default=False, verbose_name='Блокирует работу')),
                ('requires_attention', models.BooleanField(default=False, verbose_name='Требует внимания')),
                ('requires_reason', models.BooleanField(default=False, verbose_name='Требует причину')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Финальное состояние')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние техники',
                'verbose_name_plural': 'Состояния техники',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
