# Generated by Django 6.0.6 on 2026-07-12 04:27

from django.db import migrations, models


def seed_excavator_fuel_limits(apps, schema_editor):
    EquipmentModel = apps.get_model('references', 'EquipmentModel')
    for equipment_model in EquipmentModel.objects.select_related('equipment_type'):
        type_name = (equipment_model.equipment_type.name or '').lower()
        model_name = (equipment_model.name or '').lower()
        if 'экскаватор' not in type_name:
            continue
        if '3000' in model_name:
            equipment_model.fuel_capacity_limit_l = 5000
        elif '4000' in model_name:
            equipment_model.fuel_capacity_limit_l = 7000
        else:
            continue
        equipment_model.save(update_fields=['fuel_capacity_limit_l'])


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_update_free_color_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='fuel_capacity_limit_l',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальное фактическое показание остатка топлива для открытия и закрытия смены.', null=True, verbose_name='Допустимый объем топлива, л'),
        ),
        migrations.RunPython(seed_excavator_fuel_limits, migrations.RunPython.noop),
    ]
