# Generated by Django 6.0.6 on 2026-07-12 04:44

from django.db import migrations, models


def configure_known_fuel_limits(apps, schema_editor):
    EquipmentModel = apps.get_model('references', 'EquipmentModel')
    EquipmentModel.objects.filter(name__icontains='БелАЗ').update(fuel_capacity_limit_l=2000)
    EquipmentModel.objects.filter(name__icontains='BelAZ').update(fuel_capacity_limit_l=2000)
    EquipmentModel.objects.filter(name__icontains='NHL').update(fuel_capacity_limit_l=3000)


def clear_known_fuel_limits(apps, schema_editor):
    EquipmentModel = apps.get_model('references', 'EquipmentModel')
    EquipmentModel.objects.filter(name__icontains='БелАЗ').update(fuel_capacity_limit_l=None)
    EquipmentModel.objects.filter(name__icontains='BelAZ').update(fuel_capacity_limit_l=None)
    EquipmentModel.objects.filter(name__icontains='NHL').update(fuel_capacity_limit_l=None)


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_update_free_color_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='fuel_capacity_limit_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальный остаток топлива, л'),
        ),
        migrations.RunPython(configure_known_fuel_limits, clear_known_fuel_limits),
    ]
