# Generated by Django 6.0.6 on 2026-09-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_assign_truck_fuel_limits'),
        ('users', '0024_employee_contractor_access_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='contractor_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='users.contractororganization', verbose_name='Организация-подрядчик'),
        ),
    ]
