server {
    listen 80;
    listen [::]:80;
    server_name qa-driver.driverform.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name qa-driver.driverform.ru;

    ssl_certificate /etc/letsencrypt/live/qa-driver.driverform.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qa-driver.driverform.ru/privkey.pem;

    client_max_body_size 25m;

    location /static/ {
        alias /srv/accounting-mvp-excavator-qa/staticfiles/;
    }

    location /media/ {
        alias /srv/accounting-mvp-excavator-qa/media/;
    }

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://unix:/run/accounting-mvp-excavator-qa/app.sock;
    }
}
