from django.urls import path

from .views import (
    legacy_settlement_entry_view,
    legacy_settlement_login_view,
    legacy_settlement_service_worker_view,
    settlement_employee_search_view,
    settlement_employee_detail_view,
    settlement_control_acquire_view,
    settlement_control_heartbeat_view,
    settlement_control_release_view,
    settlement_auto_preview_apply_view,
    settlement_auto_preview_apply_day_view,
    settlement_auto_preview_apply_night_view,
    settlement_auto_preview_confirm_view,
    settlement_auto_preview_create_view,
    settlement_auto_preview_exclude_view,
    settlement_auto_preview_move_view,
    settlement_auto_preview_restore_view,
    settlement_auto_state_view,
    settlement_arrival_roster_create_cohort_view,
    settlement_arrival_roster_create_preview_view,
    settlement_arrival_roster_routing_view,
    settlement_login_view,
    settlement_manifest_view,
    settlement_map_view,
    settlement_occupancy_create_view,
    settlement_service_worker_view,
)


urlpatterns = [
    path(
        'clerk/manifest.webmanifest',
        settlement_manifest_view,
        name='clerk_manifest',
    ),
    path(
        'clerk/sw.js',
        settlement_service_worker_view,
        name='clerk_service_worker',
    ),
    path('clerk/login/', settlement_login_view, name='clerk_login'),
    path(
        'clerk/arrival-roster-routing/',
        settlement_arrival_roster_routing_view,
        name='settlement_arrival_roster_routing',
    ),
    path(
        'clerk/arrival-roster-routing/<int:batch_id>/create-cohort/',
        settlement_arrival_roster_create_cohort_view,
        name='settlement_arrival_roster_create_cohort',
    ),
    path(
        'clerk/arrival-roster-cohorts/<int:cohort_id>/create-preview/',
        settlement_arrival_roster_create_preview_view,
        name='settlement_arrival_roster_create_preview',
    ),
    path('clerk/', settlement_map_view, name='clerk_home'),
    path('clerk/settlement/', settlement_map_view, name='settlement_map'),
    path(
        'clerk/settlement/control/acquire/',
        settlement_control_acquire_view,
        name='settlement_control_acquire',
    ),
    path(
        'clerk/settlement/control/heartbeat/',
        settlement_control_heartbeat_view,
        name='settlement_control_heartbeat',
    ),
    path(
        'clerk/settlement/control/release/',
        settlement_control_release_view,
        name='settlement_control_release',
    ),
    path(
        'clerk/settlement/auto/state/',
        settlement_auto_state_view,
        name='settlement_auto_state',
    ),
    path(
        'clerk/settlement/auto/preview/create/',
        settlement_auto_preview_create_view,
        name='settlement_auto_preview_create',
    ),
    path(
        'clerk/settlement/auto/preview/confirm/',
        settlement_auto_preview_confirm_view,
        name='settlement_auto_preview_confirm',
    ),
    path(
        'clerk/settlement/auto/preview/move/',
        settlement_auto_preview_move_view,
        name='settlement_auto_preview_move',
    ),
    path(
        'clerk/settlement/auto/preview/exclude/',
        settlement_auto_preview_exclude_view,
        name='settlement_auto_preview_exclude',
    ),
    path(
        'clerk/settlement/auto/preview/restore/',
        settlement_auto_preview_restore_view,
        name='settlement_auto_preview_restore',
    ),
    path(
        'clerk/settlement/auto/preview/apply/',
        settlement_auto_preview_apply_view,
        name='settlement_auto_preview_apply',
    ),
    path(
        'clerk/settlement/auto/preview/apply/night/',
        settlement_auto_preview_apply_night_view,
        name='settlement_auto_preview_apply_night',
    ),
    path(
        'clerk/settlement/auto/preview/apply/day/',
        settlement_auto_preview_apply_day_view,
        name='settlement_auto_preview_apply_day',
    ),
    path(
        'clerk/settlement/employees/search/',
        settlement_employee_search_view,
        name='settlement_employee_search',
    ),
    path(
        'clerk/settlement/employees/<int:employee_id>/',
        settlement_employee_detail_view,
        name='settlement_employee_detail',
    ),
    path(
        'clerk/settlement/occupancies/',
        settlement_occupancy_create_view,
        name='settlement_occupancy_create',
    ),
    path(
        'settlement/manifest.webmanifest',
        settlement_manifest_view,
        name='legacy_settlement_manifest',
    ),
    path(
        'settlement/sw.js',
        legacy_settlement_service_worker_view,
        name='legacy_settlement_service_worker',
    ),
    path(
        'settlement/login/',
        legacy_settlement_login_view,
        name='legacy_settlement_login',
    ),
    path(
        'settlement/',
        legacy_settlement_entry_view,
        name='legacy_settlement_entry',
    ),
    path(
        'settlement/employees/search/',
        settlement_employee_search_view,
        name='legacy_settlement_employee_search',
    ),
    path(
        'settlement/occupancies/',
        settlement_occupancy_create_view,
        name='legacy_settlement_occupancy_create',
    ),
]
