from django.urls import path

from .pwa_views import (
    management_manifest_view,
    management_service_worker_view,
    mechanic_manifest_view,
    mechanic_service_worker_view,
    oup_manifest_view,
    oup_service_worker_view,
    system_admin_manifest_view,
    system_admin_service_worker_view,
)
from .oup_views import (
    oup_employee_create_view,
    oup_employee_access_deactivate_view,
    oup_employee_access_issue_view,
    oup_employee_detail_view,
    oup_employee_dismiss_view,
    oup_employees_view,
    oup_home_view,
    oup_logs_view,
    oup_shift_close_view,
    oup_shift_start_view,
    oup_temporary_work_transfer_review_view,
)
from .live_monitor_views import (
    application_session_heartbeat_view,
    system_admin_force_close_shift_view,
    system_admin_force_end_sessions_view,
    system_admin_live_monitor_view,
)
from .start_views import universal_start_view
from .native_handoff import (
    native_handoff_assetlinks_view,
    native_handoff_open_view,
    native_handoff_redeem_view,
)
from .client_errors import client_error_report_view
from .field_test_views import system_admin_field_test_view
from .enter_employee_views import system_admin_enter_employee_view
from .push_views import (
    push_mark_shown_view,
    push_pending_view,
    push_public_key_view,
    push_subscribe_view,
    push_test_view,
    push_unsubscribe_view,
)
from .views import (
    activate_access_view,
    app_catalog_qr_view,
    app_catalog_view,
    driver_accept_assignment_view,
    driver_downtime_action_view,
    driver_close_shift_view,
    driver_manifest_view,
    driver_registration_view,
    driver_service_worker_view,
    driver_shift_view,
    interface_map_view,
    login_view,
    logout_view,
    reclaim_role_session_view,
    role_home_view,
    system_admin_access_action_view,
    system_admin_change_access_role_view,
    system_admin_cancel_temporary_work_transfer_view,
    system_admin_access_export_view,
    system_admin_conflict_action_view,
    system_admin_conflicts_view,
    system_admin_conflict_export_view,
    system_admin_dashboard_view,
    system_admin_employee_create_view,
    system_admin_employee_detail_view,
    system_admin_employee_export_view,
    system_admin_employee_status_action_view,
    system_admin_employees_view,
    system_admin_exports_view,
    system_admin_generate_access_view,
    system_admin_logs_view,
    system_admin_undo_oup_action_view,
    system_admin_log_export_view,
    system_admin_reference_detail_view,
    system_admin_references_view,
    system_admin_reset_shift_test_data_view,
)

urlpatterns = [
    path('.well-known/assetlinks.json', native_handoff_assetlinks_view, name='native_handoff_assetlinks'),
    path('native-handoff/open/', native_handoff_open_view, name='native_handoff_open'),
    path('native-handoff/redeem/', native_handoff_redeem_view, name='native_handoff_redeem'),
    path('session-heartbeat/', application_session_heartbeat_view, name='application_session_heartbeat'),
    path('push/key/', push_public_key_view, name='push_public_key'),
    path('push/subscribe/', push_subscribe_view, name='push_subscribe'),
    path('push/unsubscribe/', push_unsubscribe_view, name='push_unsubscribe'),
    path('push/pending/', push_pending_view, name='push_pending'),
    path('push/shown/', push_mark_shown_view, name='push_mark_shown'),
    path('push/test/', push_test_view, name='push_test'),
    path('client-error/', client_error_report_view, name='client_error_report'),
    path('', login_view, name='login'),
    path('activate-access/', activate_access_view, name='activate_access'),
    path('reclaim-session/', reclaim_role_session_view, name='reclaim_role_session'),
    # Общий вход: одна ссылка на всех, система сама подскажет нужное приложение.
    path('start/', universal_start_view, name='universal_start'),
    path('apps/', app_catalog_view, name='app_catalog'),
    path('apps/qr/<slug:role_code>/', app_catalog_qr_view, name='app_catalog_qr'),
    path('interfaces/', interface_map_view, name='interface_map'),
    path('home/', role_home_view, name='role_home'),
    path('oup/', oup_home_view, name='oup_home'),
    path('oup/employees/', oup_employees_view, name='oup_employees'),
    path('oup/employees/new/', oup_employee_create_view, name='oup_employee_create'),
    path('oup/employees/<int:employee_id>/', oup_employee_detail_view, name='oup_employee_detail'),
    path('oup/employees/<int:employee_id>/access/issue/', oup_employee_access_issue_view, name='oup_employee_access_issue'),
    path('oup/accesses/<int:access_id>/deactivate/', oup_employee_access_deactivate_view, name='oup_employee_access_deactivate'),
    path('oup/employees/<int:employee_id>/dismiss/', oup_employee_dismiss_view, name='oup_employee_dismiss'),
    path('oup/transfers/<int:transfer_id>/<str:action>/', oup_temporary_work_transfer_review_view, name='oup_temporary_work_transfer_review'),
    path('oup/dismissed/', oup_employees_view, {'scope': 'dismissed'}, name='oup_dismissed_employees'),
    path('oup/log/', oup_logs_view, name='oup_logs'),
    path('oup/shift/start/', oup_shift_start_view, name='oup_shift_start'),
    path('oup/shift/close/', oup_shift_close_view, name='oup_shift_close'),
    path('oup.webmanifest', oup_manifest_view, name='oup_manifest'),
    path('oup-sw.js', oup_service_worker_view, name='oup_service_worker'),
    path('mechanic.webmanifest', mechanic_manifest_view, name='mechanic_manifest'),
    path('mechanic-sw.js', mechanic_service_worker_view, name='mechanic_service_worker'),
    path('management.webmanifest', management_manifest_view, name='management_manifest'),
    path('management-sw.js', management_service_worker_view, name='management_service_worker'),
    path('system-admin.webmanifest', system_admin_manifest_view, name='system_admin_manifest'),
    path('system-admin-sw.js', system_admin_service_worker_view, name='system_admin_service_worker'),
    path('driver.webmanifest', driver_manifest_view, name='driver_manifest'),
    path('driver-sw.js', driver_service_worker_view, name='driver_service_worker'),
    path('driver/', driver_shift_view, name='driver_work'),
    path('driver/registration/', driver_registration_view, name='driver_registration'),
    path('driver/shift/', driver_shift_view, name='driver_shift'),
    path('driver/shift/close/', driver_close_shift_view, name='driver_close_shift'),
    path('driver/downtime/', driver_downtime_action_view, name='driver_downtime_action'),
    path('driver/assignment/<int:assignment_id>/accept/', driver_accept_assignment_view, name='driver_accept_assignment'),
    path('system-admin/', system_admin_dashboard_view, name='system_admin_dashboard'),
    path('system-admin/live/', system_admin_live_monitor_view, name='system_admin_live_monitor'),
    path('system-admin/enter/', system_admin_enter_employee_view, name='system_admin_enter_employee'),
    path('system-admin/field-test/', system_admin_field_test_view, name='system_admin_field_test'),
    path(
        'system-admin/live/shifts/<int:shift_id>/force-close/',
        system_admin_force_close_shift_view,
        name='system_admin_force_close_shift',
    ),
    path(
        'system-admin/live/accesses/<int:access_id>/force-end/',
        system_admin_force_end_sessions_view,
        name='system_admin_force_end_sessions',
    ),
    path('system-admin/reset-shift-test-data/', system_admin_reset_shift_test_data_view, name='system_admin_reset_shift_test_data'),
    path('system-admin/employees/', system_admin_employees_view, name='system_admin_employees'),
    path('system-admin/references/', system_admin_references_view, name='system_admin_references'),
    path('system-admin/references/<slug:reference_code>/', system_admin_reference_detail_view, name='system_admin_reference_detail'),
    path('system-admin/conflicts/', system_admin_conflicts_view, name='system_admin_conflicts'),
    path('system-admin/conflicts/<int:conflict_id>/<str:action>/', system_admin_conflict_action_view, name='system_admin_conflict_action'),
    path('system-admin/logs/', system_admin_logs_view, name='system_admin_logs'),
    path('system-admin/logs/<int:log_id>/undo-oup/', system_admin_undo_oup_action_view, name='system_admin_undo_oup_action'),
    path('system-admin/exports/', system_admin_exports_view, name='system_admin_exports'),
    path('system-admin/employees/create/', system_admin_employee_create_view, name='system_admin_employee_create'),
    path('system-admin/employees/<int:employee_id>/', system_admin_employee_detail_view, name='system_admin_employee_detail'),
    path('system-admin/employees/<int:employee_id>/generate-access/', system_admin_generate_access_view, name='system_admin_generate_access'),
    path('system-admin/accesses/<int:access_id>/change-role/', system_admin_change_access_role_view, name='system_admin_change_access_role'),
    path(
        'system-admin/transfers/<int:transfer_id>/cancel/',
        system_admin_cancel_temporary_work_transfer_view,
        name='system_admin_temporary_work_transfer_cancel',
    ),
    path('system-admin/employees/<int:employee_id>/<str:action>/', system_admin_employee_status_action_view, name='system_admin_employee_status_action'),
    path('system-admin/accesses/<int:access_id>/<str:action>/', system_admin_access_action_view, name='system_admin_access_action'),
    path('system-admin/export/employees/', system_admin_employee_export_view, name='system_admin_employee_export'),
    path('system-admin/export/accesses/', system_admin_access_export_view, name='system_admin_access_export'),
    path('system-admin/export/logs/', system_admin_log_export_view, name='system_admin_log_export'),
    path('system-admin/export/conflicts/', system_admin_conflict_export_view, name='system_admin_conflict_export'),
    path('logout/', logout_view, name='logout'),
]
