from django.urls import path

from .views import (
    activate_access_view,
    driver_accept_assignment_view,
    driver_close_shift_view,
    driver_registration_view,
    driver_shift_view,
    interface_map_view,
    login_view,
    logout_view,
    role_home_view,
    system_admin_access_action_view,
    system_admin_access_export_view,
    system_admin_conflict_action_view,
    system_admin_conflicts_view,
    system_admin_conflict_export_view,
    system_admin_dashboard_view,
    system_admin_employee_create_view,
    system_admin_employee_detail_view,
    system_admin_employee_export_view,
    system_admin_employee_status_action_view,
    system_admin_employees_view,
    system_admin_generate_access_view,
    system_admin_logs_view,
    system_admin_log_export_view,
    system_admin_references_view,
)

urlpatterns = [
    path('', login_view, name='login'),
    path('activate-access/', activate_access_view, name='activate_access'),
    path('interfaces/', interface_map_view, name='interface_map'),
    path('home/', role_home_view, name='role_home'),
    path('driver/registration/', driver_registration_view, name='driver_registration'),
    path('driver/shift/', driver_shift_view, name='driver_shift'),
    path('driver/shift/close/', driver_close_shift_view, name='driver_close_shift'),
    path('driver/assignment/<int:assignment_id>/accept/', driver_accept_assignment_view, name='driver_accept_assignment'),
    path('system-admin/', system_admin_dashboard_view, name='system_admin_dashboard'),
    path('system-admin/employees/', system_admin_employees_view, name='system_admin_employees'),
    path('system-admin/references/', system_admin_references_view, name='system_admin_references'),
    path('system-admin/conflicts/', system_admin_conflicts_view, name='system_admin_conflicts'),
    path('system-admin/conflicts/<int:conflict_id>/<str:action>/', system_admin_conflict_action_view, name='system_admin_conflict_action'),
    path('system-admin/logs/', system_admin_logs_view, name='system_admin_logs'),
    path('system-admin/employees/create/', system_admin_employee_create_view, name='system_admin_employee_create'),
    path('system-admin/employees/<int:employee_id>/', system_admin_employee_detail_view, name='system_admin_employee_detail'),
    path('system-admin/employees/<int:employee_id>/generate-access/', system_admin_generate_access_view, name='system_admin_generate_access'),
    path('system-admin/employees/<int:employee_id>/<str:action>/', system_admin_employee_status_action_view, name='system_admin_employee_status_action'),
    path('system-admin/accesses/<int:access_id>/<str:action>/', system_admin_access_action_view, name='system_admin_access_action'),
    path('system-admin/export/employees/', system_admin_employee_export_view, name='system_admin_employee_export'),
    path('system-admin/export/accesses/', system_admin_access_export_view, name='system_admin_access_export'),
    path('system-admin/export/logs/', system_admin_log_export_view, name='system_admin_log_export'),
    path('system-admin/export/conflicts/', system_admin_conflict_export_view, name='system_admin_conflict_export'),
    path('logout/', logout_view, name='logout'),
]
