# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название вахты')),
                ('starts_on', models.DateField(verbose_name='Дата начала')),
                ('ends_on', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вахта',
                'verbose_name_plural': 'Вахты',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная'), ('night', 'Ночная')], max_length=16, verbose_name='Смена')),
                ('opened_at', models.DateTimeField(verbose_name='Открыта')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('is_service_closed', models.BooleanField(default=False, verbose_name='Служебное закрытие')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to='users.employee', verbose_name='Кто закрыл')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Сотрудник')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_shifts', to='users.employee', verbose_name='Кто открыл')),
                ('watch_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.watchperiod', verbose_name='Вахта')),
            ],
            options={
                'verbose_name': 'Смена сотрудника',
                'verbose_name_plural': 'Смены сотрудников',
                'ordering': ['-opened_at'],
            },
        ),
    ]
