# Generated by Django 6.0.6 on 2026-06-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='end_engine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Моточасы на конец'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='end_fuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Топливо на конец'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='end_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег на конец'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.equipment', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='start_engine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Моточасы на начало'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='start_fuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Топливо на начало'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='start_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег на начало'),
        ),
    ]
