# Generated by Django 6.0.6 on 2026-07-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_remove_in_transit_and_rename_free'),
        ('shifts', '0002_employeeshift_end_engine_hours_and_more'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная'), ('night', 'Ночная')], max_length=16, verbose_name='Смена')),
                ('name', models.CharField(default='Сменный план', max_length=128, verbose_name='Название плана')),
                ('plan_trips', models.PositiveIntegerField(blank=True, null=True, verbose_name='План рейсов')),
                ('plan_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='План объема, м3')),
                ('plan_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='План тоннажа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_plans', to='users.employee', verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Сменный план',
                'verbose_name_plural': 'Сменные планы',
                'ordering': ['-date', 'shift_type', 'name'],
                'unique_together': {('date', 'shift_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_trips', models.PositiveIntegerField(blank=True, null=True, verbose_name='План рейсов')),
                ('plan_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='План объема, м3')),
                ('plan_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='План тоннажа')),
                ('calculation_mode', models.CharField(choices=[('trips', 'По рейсам'), ('volume_m3', 'По объему, м3'), ('tonnage', 'По тоннажу'), ('mixed', 'Смешанный')], default='volume_m3', max_length=16, verbose_name='Расчет выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_shift_plans', to='users.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_plans', to='references.equipment', verbose_name='Техника')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plans', to='shifts.shiftplan', verbose_name='Сменный план')),
            ],
            options={
                'verbose_name': 'План техники на смену',
                'verbose_name_plural': 'Планы техники на смену',
                'ordering': ['shift_plan__date', 'shift_plan__shift_type', 'equipment__garage_number'],
                'unique_together': {('shift_plan', 'equipment')},
            },
        ),
    ]
