# Generated by Django 6.0.6 on 2026-07-08 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_equipment_plan_groups(apps, schema_editor):
    EquipmentPlanGroup = apps.get_model('shifts', 'EquipmentPlanGroup')
    Equipment = apps.get_model('references', 'Equipment')

    group_defaults = {
        'belaz_trucks': {
            'name': 'Самосвалы БелАЗ',
            'calculation_mode': 'trips',
            'comment': 'Стартовая группа для ежесменного плана самосвалов БелАЗ. Значение плана задает администратор.',
        },
        'nhl_trucks': {
            'name': 'Самосвалы NHL',
            'calculation_mode': 'trips',
            'comment': 'Стартовая группа для ежесменного плана самосвалов NHL. Значение плана задает администратор.',
        },
        'excavators_4000': {
            'name': 'Экскаваторы 4000',
            'calculation_mode': 'volume_m3',
            'comment': 'Стартовая группа для экскаваторов 1 и 8. Значение плана в м3 задает администратор.',
        },
        'excavators_3000': {
            'name': 'Экскаваторы 3000',
            'calculation_mode': 'volume_m3',
            'comment': 'Стартовая группа для остальных экскаваторов. Значение плана в м3 задает администратор.',
        },
    }
    groups = {}
    for code, defaults in group_defaults.items():
        group, _ = EquipmentPlanGroup.objects.get_or_create(
            code=code,
            defaults={
                'name': defaults['name'],
                'calculation_mode': defaults['calculation_mode'],
                'is_active': False,
                'comment': defaults['comment'],
            },
        )
        groups[code] = group

    for equipment in Equipment.objects.select_related('equipment_type', 'model').all():
        type_name = (getattr(equipment.equipment_type, 'name', '') or '').lower()
        model_name = (getattr(equipment.model, 'name', '') or '').lower()
        garage_number = str(equipment.garage_number or '')
        garage_digits = ''.join(char for char in garage_number if char.isdigit())
        target_code = ''

        if 'самосвал' in type_name:
            if 'nhl' in model_name or 'nte' in model_name:
                target_code = 'nhl_trucks'
            elif 'белаз' in model_name or 'belaz' in model_name:
                target_code = 'belaz_trucks'
        elif 'экскаватор' in type_name:
            if garage_digits in {'1', '8'} or '4000' in model_name:
                target_code = 'excavators_4000'
            else:
                target_code = 'excavators_3000'

        if target_code:
            groups[target_code].equipment.add(equipment)


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_remove_in_transit_and_rename_free'),
        ('shifts', '0004_shiftplan_plan_scope'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='plan_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='План назначен'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='plan_calculation_mode',
            field=models.CharField(blank=True, choices=[('trips', 'По рейсам'), ('volume_m3', 'По объему, м3'), ('tonnage', 'По тоннажу'), ('mixed', 'Смешанный')], max_length=16, verbose_name='Тип расчета snapshot'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='plan_group_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Группа плана snapshot'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='plan_status',
            field=models.CharField(blank=True, choices=[('assigned', 'План назначен'), ('no_plan_group', 'Нет группы плана'), ('no_active_plan', 'Нет активного плана')], max_length=32, verbose_name='Статус плана'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='plan_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Значение плана snapshot'),
        ),
        migrations.CreateModel(
            name='EquipmentPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Группа техники')),
                ('calculation_mode', models.CharField(choices=[('trips', 'По рейсам'), ('volume_m3', 'По объему, м3'), ('tonnage', 'По тоннажу'), ('mixed', 'Смешанный')], default='trips', max_length=16, verbose_name='Тип расчета')),
                ('plan_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Значение плана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('active_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала действия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('equipment', models.ManyToManyField(blank=True, related_name='plan_groups', to='references.equipment', verbose_name='Техника в группе')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment_plan_groups', to='users.employee', verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Ежесменный план техники',
                'verbose_name_plural': 'Ежесменные планы техники',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='plan_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_snapshots', to='shifts.equipmentplangroup', verbose_name='Группа плана'),
        ),
        migrations.RunPython(seed_equipment_plan_groups, migrations.RunPython.noop),
    ]
