# Generated by Django 6.0.6 on 2026-07-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_update_free_color_semantics'),
        ('shifts', '0006_reconcile_equipment_plan_groups'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='План выполнен', max_length=128, verbose_name='Название')),
                ('image', models.ImageField(upload_to='achievement_prizes/', verbose_name='Призовая картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Приз за выполнение плана',
                'verbose_name_plural': 'Призы за выполнение плана',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_at_unlock', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Процент при разблокировке')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Разблокирована')),
                ('shown_at', models.DateTimeField(blank=True, null=True, verbose_name='Показана')),
                ('employee_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_unlocks', to='shifts.employeeshift', verbose_name='Смена сотрудника')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_unlocks', to='references.equipment', verbose_name='Техника')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='shifts.achievementprize', verbose_name='Приз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_unlocks', to='users.employee', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Разблокировка приза',
                'verbose_name_plural': 'Разблокировки призов',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'equipment', 'employee_shift', 'prize'), name='unique_achievement_unlock_per_shift_prize')],
            },
        ),
    ]
