# Generated by Django 6.0.6 on 2026-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_update_free_color_semantics'),
        ('shifts', '0007_achievementprize_achievementunlock'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('employee',), name='unique_open_shift_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), ('equipment__isnull', False)), fields=('equipment',), name='unique_open_shift_per_equipment'),
        ),
    ]
