# Generated by Django 6.0.6 on 2026-07-11 04:44

from django.db import migrations, models
from django.utils import timezone


def close_duplicate_open_shifts(apps, schema_editor):
    EmployeeShift = apps.get_model('shifts', 'EmployeeShift')
    open_shifts = EmployeeShift.objects.filter(closed_at__isnull=True)
    duplicate_employee_ids = (
        open_shifts.values('employee_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('employee_id', flat=True)
    )
    duplicate_equipment_ids = (
        open_shifts.exclude(equipment_id=None)
        .values('equipment_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('equipment_id', flat=True)
    )

    duplicate_shift_ids = set()
    for employee_id in duplicate_employee_ids:
        shift_ids = list(
            open_shifts.filter(employee_id=employee_id)
            .order_by('-opened_at', '-id')
            .values_list('id', flat=True)
        )
        duplicate_shift_ids.update(shift_ids[1:])
    for equipment_id in duplicate_equipment_ids:
        shift_ids = list(
            open_shifts.filter(equipment_id=equipment_id)
            .order_by('-opened_at', '-id')
            .values_list('id', flat=True)
        )
        duplicate_shift_ids.update(shift_ids[1:])

    if duplicate_shift_ids:
        EmployeeShift.objects.filter(id__in=duplicate_shift_ids).update(
            closed_at=timezone.now(),
            is_service_closed=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_update_free_color_semantics'),
        ('shifts', '0007_achievementprize_achievementunlock'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.RunPython(close_duplicate_open_shifts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('employee',), name='unique_open_shift_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), ('equipment__isnull', False)), fields=('equipment',), name='unique_open_shift_per_equipment'),
        ),
    ]
