# Generated by Django 6.0.6 on 2026-07-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_assign_excavator_fuel_limit_models'),
        ('shifts', '0008_employeeshift_unique_open_shift_per_employee_and_more'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64, verbose_name='Действие')),
                ('client_action_id', models.CharField(max_length=128, verbose_name='ID действия клиента')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ сервера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_client_actions', to='users.employee', verbose_name='Машинист')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_actions', to='shifts.employeeshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Клиентское действие со сменой',
                'verbose_name_plural': 'Клиентские действия со сменами',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('action_type', 'client_action_id'), name='unique_shift_client_action')],
            },
        ),
        migrations.CreateModel(
            name='ShiftReadingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('fuel', 'Топливо'), ('engine_hours', 'Моточасы')], max_length=32, verbose_name='Показатель')),
                ('transferred_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Переданное значение')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическое значение')),
                ('corrected_at', models.DateTimeField(auto_now_add=True, verbose_name='Скорректировано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reading_corrections', to='users.employee', verbose_name='Машинист')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reading_corrections', to='references.equipment', verbose_name='Экскаватор')),
                ('new_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_corrections', to='shifts.employeeshift', verbose_name='Новая смена')),
                ('previous_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_corrections', to='shifts.employeeshift', verbose_name='Предыдущая смена')),
            ],
            options={
                'verbose_name': 'Корректировка показаний при передаче смены',
                'verbose_name_plural': 'Корректировки показаний при передаче смены',
                'ordering': ['-corrected_at'],
                'constraints': [models.UniqueConstraint(fields=('new_shift', 'previous_shift', 'metric'), name='unique_shift_handover_metric_correction')],
            },
        ),
    ]
