# Generated by Django 6.0.6 on 2026-07-12 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_equipmentmodel_fuel_capacity_limit_l'),
        ('shifts', '0008_employeeshift_unique_open_shift_per_employee_and_more'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReadingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64, verbose_name='Поле')),
                ('inherited_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Унаследованное значение')),
                ('corrected_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Водитель')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipment', verbose_name='Самосвал')),
                ('previous_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inherited_corrections', to='shifts.employeeshift', verbose_name='Предыдущая смена')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_corrections', to='shifts.employeeshift', verbose_name='Новая смена')),
            ],
            options={
                'verbose_name': 'Исправление показаний при передаче смены',
                'verbose_name_plural': 'Исправления показаний при передаче смены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverShiftAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64, verbose_name='Тип действия')),
                ('client_action_id', models.CharField(max_length=128, verbose_name='ID действия клиента')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Водитель')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_actions', to='shifts.employeeshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Действие со сменой водителя',
                'verbose_name_plural': 'Действия со сменами водителей',
                'constraints': [models.UniqueConstraint(fields=('action_type', 'client_action_id'), name='unique_driver_shift_client_action')],
            },
        ),
    ]
