# Generated by Django 6.0.6 on 2026-07-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_assign_excavator_fuel_limit_models'),
        ('shifts', '0009_shiftclientaction_shiftreadingcorrection'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreadingcorrection',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reading_corrections', to='users.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='shiftreadingcorrection',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reading_corrections', to='references.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='shiftreadingcorrection',
            name='metric',
            field=models.CharField(choices=[('fuel', 'Топливо'), ('mileage', 'Одометр'), ('engine_hours', 'Моточасы')], max_length=32, verbose_name='Показатель'),
        ),
    ]
