# Generated by Django 6.0.6 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_employeeshift_workplace_code'),
        ('users', '0016_watchcomposition_employee_watch_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchperiod',
            name='watch_composition',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='watch_periods',
                to='users.watchcomposition',
                verbose_name='Утверждённый состав вахты',
            ),
        ),
    ]
