# Generated by Django 6.0.6 on 2026-09-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_brigade_phase_actor_accesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], max_length=16, verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='plan_scope',
            field=models.CharField(choices=[('month', 'Месячный план'), ('day_total', 'Суточный план'), ('day_shift', 'Первая смена'), ('night_shift', 'Вторая смена')], default='day_shift', max_length=16, verbose_name='Тип плана'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], default='day', max_length=16, verbose_name='Расчетная смена'),
        ),
        migrations.AlterField(
            model_name='watchperiodbrigadephaserow',
            name='phase',
            field=models.CharField(choices=[('day', 'Первая смена'), ('night', 'Вторая смена'), ('off', 'Межвахта')], max_length=16, verbose_name='Фаза бригады'),
        ),
    ]
