"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


_TRUE_ENV_VALUES = {'1', 'true', 'yes', 'on'}
_FALSE_ENV_VALUES = {'0', 'false', 'no', 'off'}


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in _TRUE_ENV_VALUES:
        return True
    if normalized in _FALSE_ENV_VALUES:
        return False
    raise ValueError(f'{name} must be a boolean value, got {value!r}')


def _env_positive_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        parsed = int(value.strip())
    except (TypeError, ValueError) as error:
        raise ValueError(
            f'{name} must be a positive integer, got {value!r}'
        ) from error
    if parsed <= 0:
        raise ValueError(
            f'{name} must be a positive integer, got {value!r}'
        )
    return parsed


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.localhost').split(',')
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# These settings stay disabled for local HTTP. Production enables them only
# when nginx is the trusted TLS-terminating proxy in front of Django.
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if _env_bool('DJANGO_SECURE_PROXY_SSL_HEADER')
    else None
)
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT')
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'users',
    'references',
    'shifts',
    'assignments',
    'trips',
    'downtimes',
    'reports',
    'portal.apps.PortalConfig',
    'rotations.apps.RotationsConfig',
    'settlement.apps.SettlementConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Только ставит cookie-признак «это наше Android-приложение». Ничего не
    # блокирует и ни на что не влияет, кроме предложения установить
    # приложение, поэтому место в цепочке некритично.
    'users.middleware.NativeAppMarkerMiddleware',
    'users.middleware.ObserverModeMiddleware',
    'users.middleware.PersonalSessionRenewalMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'users.middleware.ActiveRoleSessionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.role_app',
                'portal.context_processors.portal_context',
            ],
        },
    },
]

# Role applications deliberately use host-only cookies. Never widen these
# domains to .driverform.ru: sibling role subdomains must not share a session.
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
ROLE_APP_BASE_DOMAINS = tuple(
    domain.strip()
    for domain in os.getenv('DJANGO_ROLE_APP_BASE_DOMAINS', 'driverform.ru,localhost').split(',')
    if domain.strip()
)
ROLE_APP_HOST_ALIASES = {}
for _role_host_alias in os.getenv('DJANGO_ROLE_APP_HOST_ALIASES', '').split(','):
    _role_host_alias = _role_host_alias.strip()
    if not _role_host_alias:
        continue
    _alias_separator = _role_host_alias.rfind('=')
    if _alias_separator <= 0:
        raise ValueError(
            'DJANGO_ROLE_APP_HOST_ALIASES entries must use host=role_code'
        )
    ROLE_APP_HOST_ALIASES[
        _role_host_alias[:_alias_separator].strip().lower().strip('.')
    ] = _role_host_alias[_alias_separator + 1:].strip()
ROLE_APP_PERSONAL_SESSION_AGE = int(
    os.getenv('DJANGO_ROLE_APP_PERSONAL_SESSION_AGE', str(60 * 60 * 24 * 365))
)

# Ключи для push-уведомлений. Приватный ключ хранится только в .env на сервере;
# без него уведомления просто не отправляются, остальное работает как раньше.
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv('DJANGO_WEBPUSH_VAPID_PRIVATE_KEY', '').strip()
WEBPUSH_VAPID_PUBLIC_KEY = os.getenv('DJANGO_WEBPUSH_VAPID_PUBLIC_KEY', '').strip()
WEBPUSH_CONTACT = os.getenv('DJANGO_WEBPUSH_CONTACT', 'mailto:admin@driverform.ru').strip()

# Куда писать человеку, если система не нашла его номер. Ссылка на переписку в
# мессенджере: номер в карточке правит администратор, и адресовать надо к нему,
# а не к горному мастеру. Пустая строка — экран просто не покажет кнопку.
SUPPORT_CHAT_URL = os.getenv('DJANGO_SUPPORT_CHAT_URL', '').strip()
SUPPORT_CHAT_LABEL = os.getenv('DJANGO_SUPPORT_CHAT_LABEL', 'Написать администратору').strip()

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('DJANGO_DB_ENGINE', 'sqlite') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'accounting_mvp'),
            'USER': os.getenv('POSTGRES_USER', 'accounting_mvp'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Vladivostok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

PORTAL_CACHE_URL = os.getenv('PORTAL_CACHE_URL', '').strip()
if PORTAL_CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': PORTAL_CACHE_URL,
            'KEY_PREFIX': os.getenv('DJANGO_CACHE_KEY_PREFIX', 'accounting-mvp').strip(),
            'TIMEOUT': 300,
            'OPTIONS': {
                'socket_connect_timeout': 1,
                'socket_timeout': 1,
            },
        }
    }

# Изолированный стенд приложения экскаваторщика. Одного флага недостаточно:
# команды стенда дополнительно сверяют фактическое имя базы с ожидаемым.
EXCAVATOR_QA_ENABLED = _env_bool('EXCAVATOR_QA_ENABLED', default=False)
EXCAVATOR_QA_DATABASE_NAME = os.getenv('EXCAVATOR_QA_DATABASE_NAME', '').strip()
EXCAVATOR_QA_LABEL = os.getenv('EXCAVATOR_QA_LABEL', 'ТЕСТОВЫЙ СТЕНД').strip()
EXCAVATOR_QA_PHONE = os.getenv('EXCAVATOR_QA_PHONE', '').strip()
EXCAVATOR_QA_PIN = os.getenv('EXCAVATOR_QA_PIN', '').strip()
EXCAVATOR_QA_TICK_SECONDS = _env_positive_int('EXCAVATOR_QA_TICK_SECONDS', 2)
EXCAVATOR_QA_TRANSIT_SECONDS = _env_positive_int('EXCAVATOR_QA_TRANSIT_SECONDS', 12)
EXCAVATOR_QA_TRUCK_COUNT = _env_positive_int('EXCAVATOR_QA_TRUCK_COUNT', 4)
EXCAVATOR_QA_PLAN_TRIPS = _env_positive_int('EXCAVATOR_QA_PLAN_TRIPS', 20)
TRUCK_POST_UNLOAD_COOLDOWN_SECONDS = _env_positive_int(
    'TRUCK_POST_UNLOAD_COOLDOWN_SECONDS',
    600,
)

PORTAL_PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'
ROTATIONS_PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media' / 'rotations'
PORTAL_SITE_CODE = 'section_2'
PORTAL_PRODUCTION_DATA_PROVIDER = ''
PORTAL_WORKING_DRIVER_RATING_ENABLED = _env_bool(
    'PORTAL_WORKING_DRIVER_RATING_ENABLED',
    default=False,
)
DRIVER_WATCH_RATING_DIAGNOSTIC_API_ENABLED = _env_bool(
    'DRIVER_WATCH_RATING_DIAGNOSTIC_API_ENABLED',
    default=False,
)
DRIVER_RATING_SNAPSHOT_REFRESH_SECONDS = _env_positive_int(
    'DRIVER_RATING_SNAPSHOT_REFRESH_SECONDS',
    300,
)
DRIVER_RATING_SNAPSHOT_SOFT_STALE_SECONDS = _env_positive_int(
    'DRIVER_RATING_SNAPSHOT_SOFT_STALE_SECONDS',
    600,
)
DRIVER_RATING_SNAPSHOT_HARD_EXPIRE_SECONDS = _env_positive_int(
    'DRIVER_RATING_SNAPSHOT_HARD_EXPIRE_SECONDS',
    1800,
)
RATING_TV_SCREEN_ENABLED = _env_bool(
    'RATING_TV_SCREEN_ENABLED',
    default=False,
)
RATING_TV_QA_PREVIEW_ENABLED = _env_bool(
    'RATING_TV_QA_PREVIEW_ENABLED',
    default=False,
)
RATING_TV_QA_REPLAY_ENABLED = _env_bool(
    'RATING_TV_QA_REPLAY_ENABLED',
    default=False,
)
RATING_TV_QA_REPLAY_ARTIFACT = Path(
    os.getenv(
        'RATING_TV_QA_REPLAY_ARTIFACT',
        str(
            BASE_DIR
            / 'reports'
            / 'qa_artifacts'
            / 'driver_rating_tv_visual_replay_v1.json'
        ),
    ),
)
RATING_TV_QA_REPLAY_SHA256 = os.getenv(
    'RATING_TV_QA_REPLAY_SHA256',
    'D48D515AA3CC9341AA31357D48C49982A4C3056E3D0E1A4D141DB1A4BA9C5106',
).strip().upper()
RATING_TV_QA_FORMULA_REPLAY_DAY_ENABLED = _env_bool(
    'RATING_TV_QA_FORMULA_REPLAY_DAY_ENABLED',
    default=False,
)
RATING_TV_QA_FORMULA_REPLAY_DAY_ARTIFACT = Path(
    os.getenv(
        'RATING_TV_QA_FORMULA_REPLAY_DAY_ARTIFACT',
        str(
            BASE_DIR
            / 'reports'
            / 'qa_artifacts'
            / 'driver_rating_30d_formula_replay_v1'
            / 'driver_rating_30d_formula_replay_day_v1.json'
        ),
    ),
)
RATING_TV_QA_FORMULA_REPLAY_DAY_SHA256 = os.getenv(
    'RATING_TV_QA_FORMULA_REPLAY_DAY_SHA256',
    '2B84F8044E7C89B13AED5CE19C18D7A57EDCDBB042DD73F94419CFA934AA9DBC',
).strip().upper()
RATING_TV_QA_FORMULA_REPLAY_NIGHT_ENABLED = _env_bool(
    'RATING_TV_QA_FORMULA_REPLAY_NIGHT_ENABLED',
    default=False,
)
RATING_TV_QA_FORMULA_REPLAY_NIGHT_ARTIFACT = Path(
    os.getenv(
        'RATING_TV_QA_FORMULA_REPLAY_NIGHT_ARTIFACT',
        str(
            BASE_DIR
            / 'reports'
            / 'qa_artifacts'
            / 'driver_rating_30d_formula_replay_v1'
            / 'driver_rating_30d_formula_replay_night_v1.json'
        ),
    ),
)
RATING_TV_QA_FORMULA_REPLAY_NIGHT_SHA256 = os.getenv(
    'RATING_TV_QA_FORMULA_REPLAY_NIGHT_SHA256',
    '2E990192D581A6C9A50F9C935797B672D3F39E86FD79F6E1017587EDACB02337',
).strip().upper()
# До появления других участков весь действующий кадровый состав относится к участку № 2.
# Перед подключением второго участка здесь должен быть указан серверный провайдер
# членства, возвращающий строго ограниченный Employee QuerySet.
PORTAL_EMPLOYEE_SCOPE_PROVIDER = ''

# Отказы CSRF должны быть видны в journalctl.
#
# Django знает точную причину каждого отказа («Origin checking failed»,
# «CSRF cookie not set» и т.п.) и пишет её в логгер django.security.csrf на
# уровне WARNING — но без этой настройки логгер никуда не подключён, и в
# журнале пусто. Для человека такой отказ выглядит как «Ошибка доступа 403»
# без единой подсказки, а воспроизвести его часто не удаётся: 29.08.2026
# отказ случился при первом входе в новом Android-приложении и больше не
# повторился ни разу, в том числе при попытке пройти ровно тот же путь
# запросами с сервера. Без журнала такие разовые случаи неотличимы от
# поломки входа как таковой.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security.csrf': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
