# Generated by Django 6.0.6 on 2026-08-18 07:58

import django.core.validators
import django.db.models.deletion
import rotations.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0001_initial'),
        ('settlement', '0017_m9_preview_corrections'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalRosterNormalizedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_full_name', models.TextField(verbose_name='Исходное ФИО')),
                ('normalized_full_name', models.CharField(max_length=255, verbose_name='Нормализованное ФИО')),
                ('normalized_name_key', models.CharField(db_index=True, max_length=255, verbose_name='Ключ ФИО')),
                ('name_comment', models.TextField(blank=True, verbose_name='Комментарий из ФИО')),
                ('source_position', models.CharField(blank=True, max_length=255, verbose_name='Исходная должность')),
                ('normalized_position_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ должности')),
                ('raw_shift_hint', models.CharField(blank=True, max_length=64, verbose_name='Исходная смена-подсказка')),
                ('raw_date', models.TextField(blank=True, verbose_name='Исходная дата')),
                ('arrival_date_candidate', models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата прибытия')),
                ('date_comment', models.TextField(blank=True, verbose_name='Комментарий к дате')),
                ('route_text', models.TextField(blank=True, verbose_name='Маршрут или способ прибытия')),
                ('raw_phone', models.TextField(blank=True, verbose_name='Исходный телефон')),
                ('normalized_phones', models.JSONField(blank=True, default=list, verbose_name='Нормализованные телефоны')),
                ('comments', models.TextField(blank=True, verbose_name='Исходные пояснения')),
                ('participation_hint', models.CharField(choices=[('arriving', 'Предположительно участвует'), ('additional', 'Предположительно добавлен'), ('self_transfer', 'Предположительно прибывает самостоятельно'), ('extended', 'Предположительно продлевает вахту'), ('not_arriving', 'Предположительно не заезжает'), ('review_required', 'Требуется проверка')], default='review_required', max_length=24, verbose_name='Предполагаемое участие')),
                ('color_hint', models.JSONField(blank=True, default=dict, verbose_name='Цветовая подсказка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранена')),
            ],
            options={
                'verbose_name': 'Нормализованная строка реестра заезда',
                'verbose_name_plural': 'Нормализованные строки реестра заезда',
                'ordering': ['source_row__version_id', 'source_row__sheet_name', 'source_row__row_number'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=128, verbose_name='Исходный лист')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер строки')),
                ('row_kind', models.CharField(choices=[('header', 'Заголовок'), ('person', 'Строка человека'), ('summary', 'Сверочная строка')], max_length=16, verbose_name='Тип строки')),
                ('raw_values', models.JSONField(verbose_name='Исходные значения')),
                ('raw_styles', models.JSONField(verbose_name='Исходные стили')),
                ('row_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 строки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранена')),
            ],
            options={
                'verbose_name': 'Исходная строка реестра заезда',
                'verbose_name_plural': 'Исходные строки реестра заезда',
                'ordering': ['version_id', 'sheet_name', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('exact', 'Точное сопоставление'), ('probable', 'Вероятное сопоставление'), ('ambiguous', 'Требуется сопоставление'), ('unmatched', 'Жилец не найден'), ('conflict', 'Обнаружен конфликт')], max_length=16, verbose_name='Результат сопоставления')),
                ('method', models.CharField(max_length=64, verbose_name='Способ сопоставления')),
                ('quality', models.CharField(max_length=32, verbose_name='Качество сопоставления')),
                ('evidence', models.JSONField(default=dict, verbose_name='Доказательства сопоставления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранено')),
                ('matched_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_matches', to='settlement.settlementresident', verbose_name='Точный жилец')),
            ],
            options={
                'verbose_name': 'Результат сопоставления реестра заезда',
                'verbose_name_plural': 'Результаты сопоставления реестра заезда',
                'ordering': ['version_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterMatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Связана')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_links', to='rotations.arrivalrostermatch', verbose_name='Результат сопоставления')),
                ('normalized_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='match_link', to='rotations.arrivalrosternormalizedrow', verbose_name='Нормализованная строка')),
            ],
            options={
                'verbose_name': 'Связь результата с исходной строкой',
                'verbose_name_plural': 'Связи результатов с исходными строками',
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterParserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код профиля')),
                ('version', models.PositiveIntegerField(verbose_name='Версия профиля')),
                ('configuration', models.JSONField(verbose_name='Снимок правил разбора')),
                ('configuration_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 правил разбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Профиль разбора реестра заезда',
                'verbose_name_plural': 'Профили разбора реестра заезда',
                'ordering': ['code', 'version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uniq_arrival_profile_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='arrival_profile_version_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 файла')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='Размер файла')),
                ('content_type', models.CharField(max_length=128, verbose_name='Тип содержимого')),
                ('file', models.FileField(storage=rotations.storage.ArrivalRosterPrivateStorage(), upload_to='arrival-rosters/', verbose_name='Закрытый исходный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_arrival_roster_files', to='users.employeeaccess', verbose_name='Точный доступ загрузившего')),
            ],
            options={
                'verbose_name': 'Исходный файл реестра заезда',
                'verbose_name_plural': 'Исходные файлы реестров заезда',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='arrivalrosternormalizedrow',
            name='source_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized', to='rotations.arrivalrostersourcerow', verbose_name='Исходная строка'),
        ),
        migrations.CreateModel(
            name='ArrivalRosterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review_required', 'Требуется проверка')], db_index=True, default='review_required', max_length=24, verbose_name='Состояние')),
                ('source_row_count', models.PositiveIntegerField(default=0, verbose_name='Исходных строк')),
                ('normalized_row_count', models.PositiveIntegerField(default=0, verbose_name='Распознано строк')),
                ('blocking_issue_count', models.PositiveIntegerField(default=0, verbose_name='Блокирующих замечаний')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='Предупреждений')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Неизменяемый снимок результата')),
                ('snapshot_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(regex='^$|^[0-9a-f]{64}$')], verbose_name='SHA-256 снимка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('parser_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_versions', to='rotations.arrivalrosterparserprofile', verbose_name='Профиль разбора')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_versions', to='rotations.arrivalrostersourcefile', verbose_name='Исходный файл')),
                ('uploaded_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_arrival_roster_versions', to='users.employeeaccess', verbose_name='Точный доступ загрузившего версию')),
                ('watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_versions', to='shifts.watchperiod', verbose_name='Период вахты')),
            ],
            options={
                'verbose_name': 'Версия реестра заезда',
                'verbose_name_plural': 'Версии реестра заезда',
                'ordering': ['watch_period_id', '-version_number', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='arrivalrostersourcerow',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='rotations.arrivalrosterversion', verbose_name='Версия реестра'),
        ),
        migrations.AddField(
            model_name='arrivalrostermatch',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rotations.arrivalrosterversion', verbose_name='Версия реестра'),
        ),
        migrations.CreateModel(
            name='ArrivalRosterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение')], max_length=16, verbose_name='Важность')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Код')),
                ('message', models.CharField(max_length=255, verbose_name='Описание')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Безопасные детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обнаружено')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='rotations.arrivalrostermatch', verbose_name='Результат сопоставления')),
                ('normalized_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='rotations.arrivalrosternormalizedrow', verbose_name='Нормализованная строка')),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='rotations.arrivalrostersourcerow', verbose_name='Исходная строка')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rotations.arrivalrosterversion', verbose_name='Версия реестра')),
            ],
            options={
                'verbose_name': 'Замечание реестра заезда',
                'verbose_name_plural': 'Замечания реестра заезда',
                'ordering': ['version_id', 'severity', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Файл загружен'), ('reused', 'Повторная загрузка распознана'), ('parsed', 'Предварительная проверка завершена')], max_length=24, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Безопасные детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_events', to='users.employeeaccess', verbose_name='Точный доступ исполнителя')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rotations.arrivalrosterversion', verbose_name='Версия реестра')),
            ],
            options={
                'verbose_name': 'Событие реестра заезда',
                'verbose_name_plural': 'События реестра заезда',
                'ordering': ['version_id', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.JSONField(default=dict, verbose_name='Доказательства кандидата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранён')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='rotations.arrivalrostermatch', verbose_name='Результат сопоставления')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_match_candidates', to='settlement.settlementresident', verbose_name='Возможный жилец')),
            ],
            options={
                'verbose_name': 'Кандидат сопоставления реестра заезда',
                'verbose_name_plural': 'Кандидаты сопоставления реестра заезда',
                'constraints': [models.UniqueConstraint(fields=('match', 'resident'), name='uniq_arrival_match_candidate')],
            },
        ),
        migrations.AddIndex(
            model_name='arrivalrosternormalizedrow',
            index=models.Index(fields=['normalized_name_key'], name='arrival_norm_name_idx'),
        ),
        migrations.AddIndex(
            model_name='arrivalrosterversion',
            index=models.Index(fields=['watch_period', 'status', 'version_number'], name='arrival_ver_period_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.UniqueConstraint(fields=('watch_period', 'version_number'), name='uniq_arrival_period_version'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.UniqueConstraint(fields=('watch_period', 'source_file', 'parser_profile'), name='uniq_arrival_period_file_profile'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='arrival_version_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'review_required'])), name='arrival_version_status_t11'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrostersourcerow',
            constraint=models.UniqueConstraint(fields=('version', 'sheet_name', 'row_number'), name='uniq_arrival_source_sheet_row'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrostersourcerow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='arrival_source_row_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrostermatch',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_resident__isnull', False)), fields=('version', 'matched_resident'), name='uniq_arrival_exact_resident'),
        ),
        migrations.AddConstraint(
            model_name='arrivalrostermatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('matched_resident__isnull', False), ('status', 'exact')), models.Q(('matched_resident__isnull', True), ('status__in', ['probable', 'ambiguous', 'unmatched', 'conflict'])), _connector='OR'), name='arrival_match_result_shape'),
        ),
        migrations.AddIndex(
            model_name='arrivalrosterissue',
            index=models.Index(fields=['version', 'severity'], name='arrival_issue_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='arrivalrosterevent',
            index=models.Index(fields=['version', 'created_at'], name='arrival_event_version_idx'),
        ),
    ]
