# Generated by Django 6.0.6 on 2026-08-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0002_arrival_roster_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrosterevent',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='rotations.arrivalrosterissue', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='arrivalrosterevent',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='rotations.arrivalrostermatch', verbose_name='Сопоставление'),
        ),
        migrations.AddField(
            model_name='arrivalrosterevent',
            name='review_revision',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ревизия ручной проверки'),
        ),
        migrations.AlterField(
            model_name='arrivalrosterevent',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Файл загружен'), ('reused', 'Повторная загрузка распознана'), ('parsed', 'Предварительная проверка завершена'), ('resident_selected', 'Жилец выбран'), ('resident_cleared', 'Сопоставление отменено'), ('participation_changed', 'Участие изменено'), ('arrival_mode_changed', 'Способ прибытия изменён'), ('dates_changed', 'Даты изменены'), ('notes_changed', 'Основание или комментарий изменены'), ('issue_resolved', 'Вопрос решён'), ('issue_reopened', 'Вопрос возвращён на проверку')], max_length=24, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='ArrivalRosterIssueResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Вопрос решён')),
                ('resolution_note', models.TextField(verbose_name='Пояснение')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Ревизия')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='rotations.arrivalrosterissue', verbose_name='Вопрос')),
                ('updated_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_arrival_roster_issues', to='users.employeeaccess', verbose_name='Точный доступ табельщика')),
            ],
            options={
                'verbose_name': 'Решение вопроса реестра',
                'verbose_name_plural': 'Решения вопросов реестра',
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='arrival_resolution_revision_gte_1'), models.CheckConstraint(condition=models.Q(('resolution_note', ''), _negated=True), name='arrival_resolution_note_required')],
            },
        ),
        migrations.CreateModel(
            name='ArrivalRosterRowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_resolution', models.CharField(choices=[('unreviewed', 'Не проверено'), ('selected', 'Жилец выбран'), ('cleared', 'Сопоставление отменено')], default='unreviewed', max_length=16, verbose_name='Решение по жильцу')),
                ('participation_status', models.CharField(blank=True, choices=[('arriving', 'Заезжает'), ('not_arriving', 'Не заезжает'), ('extended', 'Продлевается'), ('additional', 'Дополнительный человек')], max_length=16, null=True, verbose_name='Участие в заезде')),
                ('arrival_mode', models.CharField(blank=True, choices=[('transfer', 'Трансфер'), ('self', 'Самостоятельно')], max_length=16, null=True, verbose_name='Способ прибытия')),
                ('arrival_on', models.DateField(blank=True, null=True, verbose_name='Дата заселения')),
                ('departure_on', models.DateField(blank=True, null=True, verbose_name='Дата выбытия')),
                ('basis', models.TextField(blank=True, verbose_name='Основание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Ревизия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='row_review', to='rotations.arrivalrostermatch', verbose_name='Исходное сопоставление')),
                ('selected_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_row_reviews', to='settlement.settlementresident', verbose_name='Выбранный жилец')),
                ('updated_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_arrival_roster_rows', to='users.employeeaccess', verbose_name='Точный доступ табельщика')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='row_reviews', to='rotations.arrivalrosterversion', verbose_name='Версия реестра')),
            ],
            options={
                'verbose_name': 'Ручная проверка строки реестра',
                'verbose_name_plural': 'Ручная проверка строк реестра',
                'ordering': ['version_id', 'match_id'],
                'indexes': [models.Index(fields=['version', 'resident_resolution'], name='arrival_review_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('selected_resident__isnull', False)), fields=('version', 'selected_resident'), name='uniq_arrival_selected_resident'), models.CheckConstraint(condition=models.Q(models.Q(('resident_resolution', 'selected'), ('selected_resident__isnull', False)), models.Q(('resident_resolution__in', ['unreviewed', 'cleared']), ('selected_resident__isnull', True)), _connector='OR'), name='arrival_review_resident_shape'), models.CheckConstraint(condition=models.Q(('arrival_on__isnull', True), ('departure_on__isnull', True), ('departure_on__gte', models.F('arrival_on')), _connector='OR'), name='arrival_review_dates_order'), models.CheckConstraint(condition=models.Q(('arrival_mode__isnull', True), ('participation_status', 'arriving'), _connector='OR'), name='arrival_review_mode_shape'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='arrival_review_revision_gte_1')],
            },
        ),
    ]
