# Generated by Django 6.0.6 on 2026-08-19

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


SHA256_PATTERN = re.compile(r'^[0-9a-f]{64}$')


def backfill_excel_source_fingerprint(apps, schema_editor):
    Version = apps.get_model('rotations', 'ArrivalRosterVersion')
    for version in Version.objects.order_by('pk').iterator():
        fingerprint = version.snapshot_sha256
        if not SHA256_PATTERN.fullmatch(fingerprint or ''):
            raise RuntimeError(
                'Нельзя доказуемо заполнить source_fingerprint версии реестра '
                f'pk={version.pk}: неизменяемый snapshot_sha256 отсутствует или повреждён.'
            )
        Version.objects.filter(pk=version.pk).update(
            source_kind='excel',
            source_fingerprint=fingerprint,
        )


def reverse_noop(apps, schema_editor):
    pass


def forward_noop(apps, schema_editor):
    pass


def block_reverse_with_employee_pool(apps, schema_editor):
    Version = apps.get_model('rotations', 'ArrivalRosterVersion')
    queryset = Version.objects.filter(source_kind='employee_pool').order_by('pk')
    count = queryset.count()
    if count:
        pks = list(queryset.values_list('pk', flat=True)[:20])
        raise RuntimeError(
            'Откат rotations.0004 запрещён: существуют версии из базы сотрудников. '
            f'count={count}, pk={pks}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0003_arrival_roster_manual_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalrosterversion',
            name='source_kind',
            field=models.CharField(
                choices=[('excel', 'Excel'), ('employee_pool', 'Из базы сотрудников')],
                db_index=True,
                default='excel',
                max_length=24,
                verbose_name='Источник версии',
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='arrivalrosterversion',
            old_name='uploaded_by_access',
            new_name='created_by_access',
        ),
        migrations.AlterField(
            model_name='arrivalrosterversion',
            name='created_by_access',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_arrival_roster_versions',
                to='users.employeeaccess',
                verbose_name='Точный доступ создавшего версию',
            ),
        ),
        migrations.AlterField(
            model_name='arrivalrosterversion',
            name='source_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='roster_versions',
                to='rotations.arrivalrostersourcefile',
                verbose_name='Исходный файл',
            ),
        ),
        migrations.AlterField(
            model_name='arrivalrosterversion',
            name='parser_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='roster_versions',
                to='rotations.arrivalrosterparserprofile',
                verbose_name='Профиль разбора',
            ),
        ),
        migrations.AddField(
            model_name='arrivalrosterversion',
            name='source_fingerprint',
            field=models.CharField(max_length=64, null=True, verbose_name='SHA-256 исходного состава'),
        ),
        migrations.RunPython(backfill_excel_source_fingerprint, reverse_noop),
        migrations.AlterField(
            model_name='arrivalrosterversion',
            name='source_fingerprint',
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')],
                verbose_name='SHA-256 исходного состава',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='arrivalrosterversion',
            name='uniq_arrival_period_file_profile',
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source_kind', 'excel')),
                fields=('watch_period', 'source_file', 'parser_profile'),
                name='uniq_arrival_period_file_profile',
            ),
        ),
        migrations.AddConstraint(
            model_name='arrivalrosterversion',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('parser_profile__isnull', False),
                        ('source_file__isnull', False),
                        ('source_kind', 'excel'),
                    ),
                    models.Q(
                        ('parser_profile__isnull', True),
                        ('source_file__isnull', True),
                        ('source_kind', 'employee_pool'),
                    ),
                    _connector='OR',
                ),
                name='arrival_version_source_shape',
            ),
        ),
        migrations.CreateModel(
            name='ArrivalRosterPoolRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_kind', models.CharField(choices=[('automatic_employee', 'Автоматически из карточки сотрудника'), ('manual_employee', 'Сотрудник добавлен вручную'), ('manual_external', 'Внешний жилец добавлен вручную')], max_length=24, verbose_name='Способ добавления')),
                ('suggested_participation', models.CharField(blank=True, choices=[('arriving', 'Заезжает'), ('not_arriving', 'Не заезжает'), ('extended', 'Продлевается'), ('additional', 'Дополнительный человек')], max_length=16, null=True, verbose_name='Предлагаемое участие')),
                ('employee_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Кадровый снимок')),
                ('resident_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок карточки жильца')),
                ('snapshot_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 снимка строки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('basis', models.TextField(blank=True, verbose_name='Основание')),
                ('created_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_arrival_roster_pool_rows', to='users.employeeaccess', verbose_name='Точный доступ табельщика')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_pool_rows', to='users.employee', verbose_name='Сотрудник')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pool_row', to='rotations.arrivalrostermatch', verbose_name='Точное сопоставление')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_pool_rows', to='settlement.settlementresident', verbose_name='Жилец')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_rows', to='rotations.arrivalrosterversion', verbose_name='Версия реестра')),
                ('watch_composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_roster_pool_rows', to='users.watchcomposition', verbose_name='Зафиксированная принадлежность к вахте')),
            ],
            options={
                'verbose_name': 'Строка пула реестра заезда',
                'verbose_name_plural': 'Строки пула реестра заезда',
                'ordering': ['version_id', 'employee_id', 'resident_id'],
                'indexes': [models.Index(fields=['version', 'origin_kind'], name='arrival_pool_origin_idx')],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('resident__isnull', False)), fields=('version', 'resident'), name='uniq_arrival_pool_resident'),
                    models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('version', 'employee'), name='uniq_arrival_pool_employee'),
                    models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('origin_kind', 'automatic_employee'), ('watch_composition__isnull', False)), models.Q(('employee__isnull', False), ('origin_kind', 'manual_employee')), models.Q(('employee__isnull', True), ('origin_kind', 'manual_external'), ('resident__isnull', False), ('watch_composition__isnull', True)), _connector='OR'), name='arrival_pool_subject_shape'),
                    models.CheckConstraint(condition=models.Q(('employee__isnull', False), ('resident__isnull', False), _connector='OR'), name='arrival_pool_subject_required'),
                    models.CheckConstraint(condition=models.Q(('origin_kind', 'automatic_employee'), models.Q(('basis', ''), _negated=True), _connector='OR'), name='arrival_pool_manual_basis_required'),
                ],
            },
        ),
        migrations.AlterField(
            model_name='arrivalrosterevent',
            name='action',
            field=models.CharField(
                choices=[('uploaded', 'Файл загружен'), ('reused', 'Повторная загрузка распознана'), ('parsed', 'Предварительная проверка завершена'), ('resident_selected', 'Жилец выбран'), ('resident_cleared', 'Сопоставление отменено'), ('participation_changed', 'Участие изменено'), ('arrival_mode_changed', 'Способ прибытия изменён'), ('dates_changed', 'Даты изменены'), ('notes_changed', 'Основание или комментарий изменены'), ('issue_resolved', 'Вопрос решён'), ('issue_reopened', 'Вопрос возвращён на проверку'), ('pool_created', 'Список сформирован из карточек сотрудников'), ('pool_employee_added', 'Сотрудник добавлен в список'), ('pool_external_added', 'Внешний жилец добавлен в список')],
                max_length=24,
                verbose_name='Действие',
            ),
        ),
        migrations.RunPython(forward_noop, block_reverse_with_employee_pool),
    ]
