# Generated by Django 6.0.6 on 2026-08-20 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0007_arrival_roster_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWatchProfileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_on', models.DateField(verbose_name='Дата вступления в силу')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('old_brigade_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Прежний номер бригады')),
                ('new_brigade_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Новый номер бригады')),
                ('basis_kind', models.CharField(choices=[('employee_application', 'Заявление сотрудника'), ('official_order', 'Официальный приказ'), ('other_official_document', 'Другой официальный документ')], max_length=32, verbose_name='Вид официального основания')),
                ('basis_number', models.CharField(max_length=128, verbose_name='Номер официального основания')),
                ('basis_date', models.DateField(verbose_name='Дата официального основания')),
                ('basis', models.TextField(verbose_name='Официальное основание')),
                ('source_snapshot', models.JSONField(verbose_name='Неизменяемый снимок источника')),
                ('source_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='SHA-256 должен содержать ровно 64 шестнадцатеричных символа.', regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 снимка источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применена')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Заменена')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('applied', 'Применена'), ('superseded', 'Заменена'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('applied_by_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_employee_watch_profile_changes', to='users.employeeaccess', verbose_name='Точный доступ применившего')),
                ('cancelled_by_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_employee_watch_profile_changes', to='users.employeeaccess', verbose_name='Точный доступ отменившего')),
                ('created_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_watch_profile_changes', to='users.employeeaccess', verbose_name='Точный доступ создателя')),
                ('effective_watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_watch_profile_changes', to='shifts.watchperiod', verbose_name='Период вступления изменения в силу')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_profile_changes', to='users.employee', verbose_name='Сотрудник')),
                ('new_watch_composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_watch_profile_changes_to_composition', to='users.watchcomposition', verbose_name='Новый состав вахты')),
                ('new_work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_watch_profile_changes_to_schedule', to='users.workschedule', verbose_name='Новый график работы')),
                ('old_watch_composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_watch_profile_changes_from_composition', to='users.watchcomposition', verbose_name='Прежний состав вахты')),
                ('old_work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_watch_profile_changes_from_schedule', to='users.workschedule', verbose_name='Прежний график работы')),
                ('superseded_by_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_employee_watch_profile_changes', to='users.employeeaccess', verbose_name='Точный доступ заменившего')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='rotations.employeewatchprofilechange', verbose_name='Заменяет версию')),
            ],
            options={
                'verbose_name': 'Изменение графика, бригады и состава вахты сотрудника',
                'verbose_name_plural': 'Изменения графика, бригады и состава вахты сотрудников',
                'ordering': ['employee_id', 'effective_on', 'version_number', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_watch_period', 'version_number'), name='uniq_employee_watch_profile_version'), models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('employee', 'effective_watch_period'), name='uniq_applied_employee_watch_profile'), models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='employee_watch_profile_version_gte_1'), models.CheckConstraint(condition=models.Q(('old_brigade_number__isnull', True), ('old_brigade_number__gte', 1), _connector='OR'), name='employee_watch_profile_old_brigade_gte_1'), models.CheckConstraint(condition=models.Q(('new_brigade_number__isnull', True), ('new_brigade_number__gte', 1), _connector='OR'), name='employee_watch_profile_new_brigade_gte_1'), models.CheckConstraint(condition=models.Q(('basis_kind__in', ['employee_application', 'official_order', 'other_official_document'])), name='employee_watch_profile_basis_kind_valid'), models.CheckConstraint(condition=models.Q(models.Q(('basis_number', ''), _negated=True), models.Q(('basis', ''), _negated=True)), name='employee_watch_profile_basis_required'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'applied', 'superseded', 'cancelled'])), name='employee_watch_profile_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('applied_by_access__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by_access__isnull', True), ('status', 'draft'), ('superseded_at__isnull', True), ('superseded_by_access__isnull', True)), models.Q(('applied_at__isnull', False), ('applied_by_access__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by_access__isnull', True), ('status', 'applied'), ('superseded_at__isnull', True), ('superseded_by_access__isnull', True)), models.Q(('applied_at__isnull', False), ('applied_by_access__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by_access__isnull', True), ('status', 'superseded'), ('superseded_at__isnull', False), ('superseded_by_access__isnull', False)), models.Q(('applied_at__isnull', True), ('applied_by_access__isnull', True), ('cancelled_at__isnull', False), ('cancelled_by_access__isnull', False), ('status', 'cancelled'), ('superseded_at__isnull', True), ('superseded_by_access__isnull', True)), _connector='OR'), name='employee_watch_profile_status_audit')],
            },
        ),
    ]
