# Generated by Django 6.0.6 on 2026-09-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0008_employee_watch_profile_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationresponse',
            name='next_shift_type',
            field=models.CharField(blank=True, choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], default='', max_length=16, verbose_name='Смена следующей вахты'),
        ),
    ]
