# Generated by Django 6.0.6 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('shifts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('cancelled', 'Отменено')], default='pending', max_length=16, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_assignments', to='users.employee', verbose_name='Кто назначил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.equipment', verbose_name='Техника')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.employeeshift', verbose_name='Смена сотрудника')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника на технику',
                'verbose_name_plural': 'Назначения сотрудников на технику',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='HaulAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('cancelled', 'Отменено')], default='pending', max_length=16, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято водителем')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employee', verbose_name='Кто назначил')),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excavator_haul_assignments', to='references.equipment', verbose_name='Экскаватор')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_haul_assignments', to='references.equipment', verbose_name='Самосвал')),
            ],
            options={
                'verbose_name': 'Назначение самосвала под экскаватор',
                'verbose_name_plural': 'Назначения самосвалов под экскаваторы',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
