# Generated by Django 6.0.6 on 2026-07-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_excavatorplacement'),
        ('references', '0003_remove_in_transit_and_rename_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatorplacement',
            name='loading_block',
            field=models.CharField(blank=True, max_length=64, verbose_name='Блок погрузки'),
        ),
        migrations.AddField(
            model_name='excavatorplacement',
            name='loading_horizon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Горизонт погрузки'),
        ),
        migrations.AddField(
            model_name='excavatorplacement',
            name='work_context_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Контекст забоя обновлен'),
        ),
        migrations.AddField(
            model_name='excavatorplacement',
            name='work_dump_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excavator_work_placements', to='references.dumppoint', verbose_name='Основная точка разгрузки'),
        ),
        migrations.AddField(
            model_name='excavatorplacement',
            name='work_rock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excavator_work_placements', to='references.rocktype', verbose_name='Порода текущего забоя'),
        ),
    ]
