# Generated by Django 6.0.6 on 2026-07-10 14:25

from datetime import timedelta

from django.db import migrations, models


def set_pending_effective_at(apps, schema_editor):
    assignment_model = apps.get_model('assignments', 'HaulAssignment')
    for assignment in assignment_model.objects.filter(status='pending', effective_at__isnull=True):
        assignment.effective_at = assignment.assigned_at + timedelta(minutes=5)
        assignment.save(update_fields=['effective_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_excavatorplacement_loading_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulassignment',
            name='action',
            field=models.CharField(choices=[('assign', 'Назначить'), ('release', 'Снять назначение')], default='assign', max_length=16, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='haulassignment',
            name='effective_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вступает в силу'),
        ),
        migrations.RunPython(set_pending_effective_at, migrations.RunPython.noop),
    ]
