# Generated by Django 6.0.6 on 2026-07-11 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_haulassignment_action_haulassignment_effective_at'),
        ('references', '0004_update_free_color_semantics'),
        ('shifts', '0007_achievementprize_achievementunlock'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_equipment_assignments', to='users.employee', verbose_name='Кто завершил'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to='users.role', verbose_name='Рабочая роль'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('day', 'Смена 1 · 07:00–19:00'), ('night', 'Смена 2 · 19:00–07:00')], max_length=16, null=True, verbose_name='Рабочая смена'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role__isnull', False), ('shift__isnull', True), ('shift_type__isnull', False), ('status', 'accepted')), fields=('employee',), name='unique_active_employee_equipment_assignment'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role__isnull', False), ('shift__isnull', True), ('shift_type__isnull', False), ('status', 'accepted')), fields=('equipment', 'shift_type'), name='unique_active_equipment_work_shift'),
        ),
    ]
