# Generated by Django 6.0.6 on 2026-07-12 21:49

import django.db.models.deletion
from django.db import migrations, models


def create_deputy_mining_manager_role(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.update_or_create(
        code='deputy_mining_manager',
        defaults={
            'name': 'Заместитель начальника горного участка',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_equipmentassignment_ended_by_and_more'),
        ('references', '0007_assign_truck_fuel_limits'),
        ('users', '0008_remove_employeeaccess_unique_employee_role_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Производственные сутки')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Ревизия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('superseded', 'Заменен новой публикацией')], default='draft', max_length=16, verbose_name='Статус')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия черновика')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crew_plans', to='users.employee', verbose_name='Кто создал')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_crew_plans', to='users.employee', verbose_name='Кто опубликовал')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_plans', to='users.role', verbose_name='Рабочая роль')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_crew_plans', to='users.employee', verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'План расстановки экипажей',
                'verbose_name_plural': 'Планы расстановки экипажей',
                'ordering': ['-work_date', 'role__name', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='CrewPlanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Смена 1 · 07:00–19:00'), ('night', 'Смена 2 · 19:00–07:00')], max_length=16, verbose_name='Рабочая смена')),
                ('baseline_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_crew_plan_slots', to='users.employee', verbose_name='Сотрудник в базовой расстановке')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_plan_slots', to='users.employee', verbose_name='Назначенный сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_plan_slots', to='references.equipment', verbose_name='Техника')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='assignments.crewplan', verbose_name='План расстановки')),
            ],
            options={
                'verbose_name': 'Слот плана расстановки',
                'verbose_name_plural': 'Слоты плана расстановки',
                'ordering': ['equipment__garage_number', 'shift_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='crewplan',
            constraint=models.UniqueConstraint(fields=('work_date', 'role', 'revision'), name='unique_crew_plan_revision'),
        ),
        migrations.AddConstraint(
            model_name='crewplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('work_date', 'role'), name='unique_draft_crew_plan'),
        ),
        migrations.AddConstraint(
            model_name='crewplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('work_date', 'role'), name='unique_published_crew_plan'),
        ),
        migrations.AddConstraint(
            model_name='crewplanslot',
            constraint=models.UniqueConstraint(fields=('plan', 'equipment', 'shift_type'), name='unique_crew_plan_equipment_shift'),
        ),
        migrations.AddConstraint(
            model_name='crewplanslot',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('plan', 'employee'), name='unique_crew_plan_employee'),
        ),
        migrations.RunPython(create_deputy_mining_manager_role, migrations.RunPython.noop),
    ]
