# Generated by Django 6.0.6 on 2026-08-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_crewplan_crewplanslot_and_more'),
        ('references', '0007_assign_truck_fuel_limits'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='source_crew_plan_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to='assignments.crewplanslot', verbose_name='Слот опубликованного плана-источника'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='source_kind',
            field=models.CharField(choices=[('unverified', 'Непроверенный или неофициальный источник'), ('deputy_published_plan', 'Опубликованный план заместителя')], default='unverified', max_length=32, verbose_name='Источник назначения'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_crew_plan_slot__isnull', False), ('source_kind', 'deputy_published_plan')), models.Q(('source_crew_plan_slot__isnull', True), ('source_kind', 'unverified')), _connector='OR'), name='assignment_source_shape_valid'),
        ),
    ]
