# Generated by Django 6.0.6 on 2026-09-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_equipment_assignment_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewplanslot',
            name='baseline_secondary_employee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='baseline_secondary_crew_plan_slots',
                to='users.employee',
                verbose_name='Дополнительный участник в базовой расстановке',
            ),
        ),
        migrations.AddField(
            model_name='crewplanslot',
            name='secondary_employee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='secondary_crew_plan_slots',
                to='users.employee',
                verbose_name='Дополнительный участник экипажа',
            ),
        ),
        migrations.AddConstraint(
            model_name='crewplanslot',
            constraint=models.UniqueConstraint(
                condition=models.Q(('secondary_employee__isnull', False)),
                fields=('plan', 'secondary_employee'),
                name='unique_crew_plan_secondary_employee',
            ),
        ),
        migrations.AddConstraint(
            model_name='crewplanslot',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('employee__isnull', True))
                    | models.Q(('secondary_employee__isnull', True))
                    | ~models.Q(('employee', models.F('secondary_employee')))
                ),
                name='crew_plan_slot_distinct_employees',
            ),
        ),
    ]
