# Generated by Django 6.0.6 on 2026-09-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_haul_assignment_handoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewplanslot',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], max_length=16, verbose_name='Рабочая смена'),
        ),
        migrations.AlterField(
            model_name='equipmentassignment',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('day', 'Первая смена'), ('night', 'Вторая смена')], max_length=16, null=True, verbose_name='Рабочая смена'),
        ),
    ]
