# TYPE  DATABASE  USER          ADDRESS          METHOD
local   all       postgres                       peer
local   all       all                            peer
host    sseqa     sseqa_app     127.0.0.1/32     scram-sha-256
host    sseqa     sseqa_maint   127.0.0.1/32     scram-sha-256
host    all       all           0.0.0.0/0        reject
host    all       all           ::0/0            reject

