data_directory = '/srv/sse-qa/postgres/data'
hba_file = '/etc/sse-qa/pg_hba.conf'
ident_file = '/etc/postgresql/16/sseqa/pg_ident.conf'
listen_addresses = '127.0.0.1'
port = 55432
max_connections = 16
superuser_reserved_connections = 3
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 32MB
effective_cache_size = 256MB
temp_file_limit = 262144
max_wal_size = 256MB
min_wal_size = 80MB
wal_compression = on
logging_collector = on
log_directory = '/srv/sse-qa/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_rotation_size = 20MB
log_truncate_on_rotation = on
log_min_duration_statement = 1000
log_temp_files = 0
log_connections = on
log_disconnections = on
password_encryption = scram-sha-256
ssl = off

