# Generated by Django 6.0.6 on 2026-07-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_normalize_department_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Отправлено без имени')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('photo', models.FileField(blank=True, upload_to='portal/messages/%Y/%m/', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('in_progress', 'В работе'), ('answered', 'Есть ответ'), ('closed', 'Закрыто')], default='sent', max_length=16, verbose_name='Статус')),
                ('response', models.TextField(blank=True, verbose_name='Ответ руководства')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_leadership_messages', to='users.employee', verbose_name='Автор')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_portal_messages', to='users.employee', verbose_name='Ответил')),
            ],
            options={
                'verbose_name': 'Обращение руководству',
                'verbose_name_plural': 'Обращения руководству',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.FileField(blank=True, upload_to='portal/suggestions/%Y/%m/', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'Принято в работу'), ('rejected', 'Отклонено')], default='new', max_length=16, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_suggestions', to='users.employee', verbose_name='Предложил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_portal_suggestions', to='users.employee', verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Предложение материала',
                'verbose_name_plural': 'Предложения материалов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыт'), ('closed', 'Завершён')], default='draft', max_length=16, verbose_name='Статус')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Анонимный опрос')),
                ('audience', models.CharField(choices=[('all', 'Все сотрудники участка № 2'), ('day_shift', 'Дневная смена'), ('night_shift', 'Ночная смена'), ('profession', 'Выбранная профессия'), ('employee', 'Выбранный сотрудник')], default='all', max_length=24, verbose_name='Кому')),
                ('target_work_category', models.CharField(blank=True, choices=[('driver', 'Водители самосвалов'), ('excavator_operator', 'Машинисты экскаваторов'), ('other', 'Остальные сотрудники')], max_length=32, verbose_name='Профессия получателей')),
                ('results_published', models.BooleanField(default=False, verbose_name='Показать итог сотрудникам')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_portal_polls', to='users.employee', verbose_name='Автор')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_portal_polls', to='users.employee', verbose_name='Открыл опрос')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_portal_polls', to='users.employee', verbose_name='Сотрудник-получатель')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220, verbose_name='Вариант ответа')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portal.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action', models.CharField(max_length=80, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_audit_actions', to='users.employee', verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Запись журнала портала',
                'verbose_name_plural': 'Журнал портала',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalStaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_author', models.BooleanField(default=False, verbose_name='Может создавать материалы')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Может редактировать материалы')),
                ('can_publish', models.BooleanField(default=False, verbose_name='Может публиковать')),
                ('receives_feedback', models.BooleanField(default=False, verbose_name='Получает обращения руководству')),
                ('is_active', models.BooleanField(default=True, verbose_name='Права активны')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_portal_permissions', to='users.employee', verbose_name='Назначил')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_staff_permission', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Редакционное право портала',
                'verbose_name_plural': 'Редакционные права портала',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=170, unique=True, verbose_name='Адрес')),
                ('publication_type', models.CharField(choices=[('news', 'Новость'), ('announcement', 'Объявление'), ('interview', 'Интервью'), ('story', 'История сотрудника'), ('achievement', 'Достижение'), ('birthday', 'Поздравление'), ('qna', 'Ответ руководства')], default='news', max_length=24, verbose_name='Тип материала')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='Статус')),
                ('visibility', models.CharField(choices=[('internal', 'Только сотрудникам'), ('public', 'Только на открытом сайте'), ('both', 'На открытом сайте и сотрудникам')], default='internal', help_text='Безопасное значение по умолчанию — только закрытая часть.', max_length=16, verbose_name='Где показывать')),
                ('audience', models.CharField(choices=[('all', 'Все сотрудники участка № 2'), ('day_shift', 'Дневная смена'), ('night_shift', 'Ночная смена'), ('profession', 'Выбранная профессия'), ('employee', 'Выбранный сотрудник')], default='all', max_length=24, verbose_name='Кому внутри портала')),
                ('target_work_category', models.CharField(blank=True, choices=[('driver', 'Водители самосвалов'), ('excavator_operator', 'Машинисты экскаваторов'), ('other', 'Остальные сотрудники')], max_length=32, verbose_name='Профессия получателей')),
                ('summary', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover_image', models.FileField(blank=True, upload_to='portal/publications/%Y/%m/', verbose_name='Обложка')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Требуется отметка «Ознакомился»')),
                ('allow_reactions', models.BooleanField(default=True, verbose_name='Разрешить реакцию «Спасибо»')),
                ('pin_to_dashboard', models.BooleanField(default=False, verbose_name='Закрепить на главной портала')),
                ('public_consent_confirmed', models.BooleanField(default=False, verbose_name='Согласие сотрудника на открытую публикацию подтверждено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_portal_publications', to='users.employee', verbose_name='Автор')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_portal_publications', to='users.employee', verbose_name='Последний редактор')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_portal_publications', to='users.employee', verbose_name='Опубликовал')),
                ('subject_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_stories', to='users.employee', verbose_name='Герой материала')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_portal_publications', to='users.employee', verbose_name='Сотрудник-получатель')),
            ],
            options={
                'verbose_name': 'Публикация портала',
                'verbose_name_plural': 'Публикации портала',
                'ordering': ['-pin_to_dashboard', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Ознакомился')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_acknowledgements', to='users.employee', verbose_name='Сотрудник')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='portal.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Ознакомление с публикацией',
                'verbose_name_plural': 'Ознакомления с публикациями',
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portal/publications/%Y/%m/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Фотография публикации',
                'verbose_name_plural': 'Фотографии публикации',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_reactions', to='users.employee', verbose_name='Сотрудник')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='portal.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Реакция на публикацию',
                'verbose_name_plural': 'Реакции на публикации',
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=64, verbose_name='Анонимный ключ участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Проголосовал')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_poll_votes', to='users.employee', verbose_name='Сотрудник (только для именного опроса)')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='portal.polloption', verbose_name='Ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='portal.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Голос в опросе',
                'verbose_name_plural': 'Голоса в опросах',
                'constraints': [models.UniqueConstraint(fields=('poll', 'voter_key'), name='unique_portal_poll_voter')],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', 'visibility', 'published_at'], name='portal_publ_status_bdfd2f_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type', 'status'], name='portal_publ_publica_76c3aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicationacknowledgement',
            constraint=models.UniqueConstraint(fields=('publication', 'employee'), name='unique_portal_publication_acknowledgement'),
        ),
        migrations.AddConstraint(
            model_name='publicationreaction',
            constraint=models.UniqueConstraint(fields=('publication', 'employee'), name='unique_portal_publication_reaction'),
        ),
    ]
