# Generated by Django 6.0.6 on 2026-07-17 21:09

import django.core.validators
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipmessage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='portal/messages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), portal.models.validate_portal_image_size], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='materialsuggestion',
            name='photo',
            field=models.ImageField(blank=True, upload_to='portal/suggestions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), portal.models.validate_portal_image_size], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='portal/publications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), portal.models.validate_portal_image_size], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image',
            field=models.ImageField(upload_to='portal/publications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), portal.models.validate_portal_image_size], verbose_name='Фотография'),
        ),
    ]
