# Generated by Django 6.0.6 on 2026-07-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_leadershipmessage_photo_and_more'),
        ('users', '0013_normalize_department_work_schedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('subject_employee__isnull', True), ('visibility', 'internal'), ('public_consent_confirmed', True), _connector='OR'), name='portal_public_story_requires_consent'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('is_mandatory', False), models.Q(('visibility', 'public'), _negated=True), _connector='OR'), name='portal_mandatory_requires_internal_visibility'),
        ),
    ]
