# Generated by Django 6.0.6 on 2026-07-29 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0007_assign_truck_fuel_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Этаж')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('standard', 'Стандартная'), ('itr', 'ИТР')], default='standard', max_length=16, verbose_name='Тип комнаты')),
                ('transfer_status', models.CharField(choices=[('transferred', 'Передана'), ('not_transferred', 'Не передана')], db_index=True, default='not_transferred', max_length=24, verbose_name='Статус передачи')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Вместимость')),
                ('corridor_side', models.CharField(choices=[('left', 'Левая сторона'), ('right', 'Правая сторона')], max_length=8, verbose_name='Сторона коридора')),
                ('side_position', models.PositiveSmallIntegerField(help_text='Порядок комнаты только внутри стороны выбранного этажа. Не задаёт соответствие номеров между этажами.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция на стороне этажа')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_rooms', to='references.dormitory', verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Физическая комната',
                'verbose_name_plural': 'Физические комнаты',
                'ordering': ['dormitory__number', 'floor', 'corridor_side', 'side_position', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Стабильный идентификатор')),
                ('block', models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('ITR', 'ИТР')], max_length=3, verbose_name='Блок')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Номер койко-места в блоке')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='settlement.physicalroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Физическое койко-место',
                'verbose_name_plural': 'Физические койко-места',
                'ordering': ['room', 'block', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='physicalroom',
            constraint=models.UniqueConstraint(fields=('dormitory', 'floor', 'number'), name='unique_physical_room_number'),
        ),
        migrations.AddConstraint(
            model_name='physicalroom',
            constraint=models.UniqueConstraint(fields=('dormitory', 'floor', 'corridor_side', 'side_position'), name='unique_physical_room_side_position'),
        ),
        migrations.AddConstraint(
            model_name='physicalroom',
            constraint=models.CheckConstraint(condition=models.Q(('floor__gte', 1), ('floor__lte', 2)), name='physical_room_floor_1_2'),
        ),
        migrations.AddConstraint(
            model_name='physicalroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 6)), name='physical_room_capacity_1_6'),
        ),
        migrations.AddConstraint(
            model_name='physicalbed',
            constraint=models.UniqueConstraint(fields=('room', 'block', 'position'), name='unique_physical_bed_in_room'),
        ),
        migrations.AddConstraint(
            model_name='physicalbed',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='physical_bed_position_1_3'),
        ),
        migrations.AddConstraint(
            model_name='physicalbed',
            constraint=models.CheckConstraint(condition=models.Q(('block__in', ['A', 'B']), models.Q(('block', 'ITR'), ('position__lte', 2)), _connector='OR'), name='physical_bed_block_position_valid'),
        ),
    ]
