# Generated by Django 6.0.6 on 2026-08-03 07:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_assign_truck_fuel_limits'),
        ('settlement', '0001_initial'),
        ('users', '0016_watchcomposition_employee_watch_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код ревизии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена')),
                ('confirmed_by_label', models.CharField(blank=True, help_text='Снимок имени или реквизитов подтвердившего лица без связи с сотрудником.', max_length=255, verbose_name='Кем подтверждена')),
                ('reason', models.TextField(verbose_name='Основание изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='settlement.settlementrevision', verbose_name='Заменяет ревизию')),
            ],
            options={
                'verbose_name': 'Ревизия расселения',
                'verbose_name_plural': 'Ревизии расселения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код якоря')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое наименование')),
                ('anchor_type', models.CharField(choices=[('equipment', 'Техника'), ('function', 'Должность или функция'), ('reserve', 'Резерв'), ('group', 'Группа'), ('service', 'Служебный'), ('protected', 'Защищённый')], max_length=16, verbose_name='Тип якоря')),
                ('function_key', models.CharField(blank=True, max_length=128, verbose_name='Код функции')),
                ('group_key', models.CharField(blank=True, max_length=128, verbose_name='Код группы')),
                ('ordinal', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер внутри группы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('archived', 'Архивный')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_anchors', to='references.equipment', verbose_name='Техника')),
                ('personnel_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_anchors', to='users.personneldepartment', verbose_name='Подразделение')),
                ('personnel_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_anchors', to='users.personnelposition', verbose_name='Кадровая должность')),
                ('archived_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_anchors', to='settlement.settlementrevision', verbose_name='Ревизия архивирования')),
                ('created_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_anchors', to='settlement.settlementrevision', verbose_name='Ревизия создания')),
            ],
            options={
                'verbose_name': 'Жилищный якорь',
                'verbose_name_plural': 'Жилищные якоря',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SettlementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('source_type', models.CharField(choices=[('document', 'Документ'), ('file', 'Файл'), ('manual', 'Ручное решение'), ('system', 'Информационная система'), ('other', 'Другой источник')], max_length=16, verbose_name='Тип источника')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('external_reference', models.CharField(blank=True, max_length=500, verbose_name='Внешняя ссылка или идентификатор')),
                ('version', models.CharField(blank=True, max_length=128, verbose_name='Версия')),
                ('document_number', models.CharField(blank=True, max_length=128, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('file_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='SHA-256 должен содержать ровно 64 шестнадцатеричных символа.', regex='^[0-9a-fA-F]{64}$')], verbose_name='SHA-256 файла')),
                ('status', models.CharField(choices=[('candidate', 'Кандидат'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('archived', 'Архивный')], db_index=True, default='candidate', max_length=16, verbose_name='Статус')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('confirmed_by_label', models.CharField(blank=True, help_text='Снимок имени или реквизитов подтвердившего лица без связи с сотрудником.', max_length=255, verbose_name='Кем подтверждён')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Источник данных расселения',
                'verbose_name_plural': 'Источники данных расселения',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('confirmed_at__isnull', False), models.Q(('confirmed_by_label', ''), _negated=True)), _connector='OR'), name='settlement_source_confirmed_meta')],
            },
        ),
        migrations.AddField(
            model_name='settlementrevision',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='settlement.settlementsource', verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='AccommodationAnchorBedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('valid_from', models.DateTimeField(verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Пустое значение означает открытый период. Окончание в период не входит.', null=True, verbose_name='Действует до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='settlement.accommodationanchor', verbose_name='Жилищный якорь')),
                ('physical_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anchor_assignments', to='settlement.physicalbed', verbose_name='Физическое койко-место')),
                ('cancelled_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_anchor_bed_assignments', to='settlement.settlementrevision', verbose_name='Ревизия отмены')),
                ('ended_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_anchor_bed_assignments', to='settlement.settlementrevision', verbose_name='Ревизия окончания')),
                ('started_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_anchor_bed_assignments', to='settlement.settlementrevision', verbose_name='Ревизия начала')),
            ],
            options={
                'verbose_name': 'Закрепление жилищного якоря за койко-местом',
                'verbose_name_plural': 'Закрепления жилищных якорей за койко-местами',
                'ordering': ['anchor', '-valid_from'],
                'indexes': [models.Index(fields=['anchor', 'status', 'valid_from'], name='anchor_bed_anchor_period_idx'), models.Index(fields=['physical_bed', 'status', 'valid_from'], name='anchor_bed_bed_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='anchor_bed_period_non_empty'), models.CheckConstraint(condition=models.Q(models.Q(('ended_revision__isnull', True), ('valid_to__isnull', True)), models.Q(('ended_revision__isnull', False), ('valid_to__isnull', False)), _connector='OR'), name='anchor_bed_end_revision_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_revision__isnull', False), ('status', 'cancelled')), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_revision__isnull', True)), _connector='OR'), name='anchor_bed_cancel_revision_consistent'), models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), ('valid_to__isnull', True)), fields=('anchor',), name='unique_open_confirmed_bed_per_anchor'), models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), ('valid_to__isnull', True)), fields=('physical_bed',), name='unique_open_confirmed_anchor_per_bed')],
            },
        ),
        migrations.AddConstraint(
            model_name='accommodationanchor',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='accommodation_anchor_ordinal_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='accommodationanchor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_revision__isnull', False), _connector='OR'), name='accommodation_anchor_archive_revision'),
        ),
        migrations.AddConstraint(
            model_name='settlementrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('effective_at__isnull', False), ('confirmed_at__isnull', False), models.Q(('confirmed_by_label', ''), _negated=True)), _connector='OR'), name='settlement_revision_confirmed_meta'),
        ),
        migrations.AddConstraint(
            model_name='settlementrevision',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('pk', models.F('supersedes_id')), _negated=True), _connector='OR'), name='settlement_revision_not_self'),
        ),
    ]
