# Generated by Django 6.0.6 on 2026-08-04 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_settlementrevision_accommodationanchor_and_more'),
        ('users', '0016_watchcomposition_employee_watch_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBedOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('permanent', 'Постоянное'), ('temporary', 'Временное'), ('proposed', 'Предложенное')], max_length=16, verbose_name='Тип закрепления')),
                ('settled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заселён')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Проживание завершено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_occupancies', to='users.employee', verbose_name='Сотрудник')),
                ('physical_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='settlement.physicalbed', verbose_name='Физическое койко-место')),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bed_occupancies', to='users.employee', verbose_name='Кто заселил')),
            ],
            options={
                'verbose_name': 'Размещение сотрудника на койко-месте',
                'verbose_name_plural': 'Размещения сотрудников на койко-местах',
                'ordering': ['-settled_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('physical_bed',), name='unique_active_employee_bed_occupancy'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('employee',), name='unique_active_employee_occupancy'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('settled_at')), _connector='OR'), name='employee_bed_occupancy_period_valid')],
            },
        ),
    ]
