# Generated by Django 6.0.6 on 2026-08-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_physical_room_sex_restriction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeebedoccupancy',
            name='unique_active_employee_bed_occupancy',
        ),
        migrations.RemoveConstraint(
            model_name='employeebedoccupancy',
            name='unique_active_employee_occupancy',
        ),
        migrations.RemoveConstraint(
            model_name='employeebedoccupancy',
            name='employee_bed_occupancy_period_valid',
        ),
    ]
