# Generated by Django 6.0.6 on 2026-08-15 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_settlement_control_lease(apps, schema_editor):
    SettlementControlLease = apps.get_model(
        'settlement',
        'SettlementControlLease',
    )
    SettlementControlLease.objects.create(scope='settlement')


def remove_settlement_control_lease(apps, schema_editor):
    SettlementControlLease = apps.get_model(
        'settlement',
        'SettlementControlLease',
    )
    SettlementControlLease.objects.filter(scope='settlement').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_remove_legacy_occupancy_constraints'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACQUIRED', 'Управление получено'), ('RELEASED', 'Управление освобождено'), ('EXPIRED', 'Срок управления истёк'), ('TAKEN_OVER', 'Управление перехвачено')], max_length=16, verbose_name='Тип события')),
                ('scope', models.CharField(max_length=64, verbose_name='Контур управления')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Произошло')),
                ('source', models.CharField(max_length=64, verbose_name='Источник')),
                ('previous_fencing_revision', models.PositiveBigIntegerField(verbose_name='Предыдущая ревизия')),
                ('new_fencing_revision', models.PositiveBigIntegerField(verbose_name='Новая ревизия')),
                ('session_metadata', models.JSONField(blank=True, default=dict, verbose_name='Безопасные метаданные сессии')),
                ('actor_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_control_events_as_actor', to='users.employeeaccess', verbose_name='Доступ инициатора')),
                ('new_owner_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_control_events_as_new_owner', to='users.employeeaccess', verbose_name='Новый владелец')),
                ('previous_owner_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_control_events_as_previous_owner', to='users.employeeaccess', verbose_name='Прежний владелец')),
            ],
            options={
                'verbose_name': 'Событие управления расселением',
                'verbose_name_plural': 'События управления расселением',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['scope', 'occurred_at'], name='settle_event_scope_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['ACQUIRED', 'RELEASED', 'EXPIRED', 'TAKEN_OVER'])), name='settlement_control_event_type_valid'), models.CheckConstraint(condition=models.Q(('new_fencing_revision__gt', models.F('previous_fencing_revision'))), name='settlement_control_event_revision_increases'), models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'TAKEN_OVER'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='settlement_takeover_reason_required')],
            },
        ),
        migrations.CreateModel(
            name='SettlementControlLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, unique=True, verbose_name='Контур управления')),
                ('owner_session_hash', models.CharField(blank=True, max_length=128, verbose_name='Хеш сессии владельца')),
                ('lease_token', models.UUIDField(blank=True, null=True, verbose_name='Токен владения')),
                ('fencing_revision', models.PositiveBigIntegerField(default=0, verbose_name='Ревизия владения')),
                ('acquired_at', models.DateTimeField(blank=True, null=True, verbose_name='Управление получено')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее подтверждение активности')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок владения истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('owner_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_control_leases', to='users.employeeaccess', verbose_name='Доступ текущего владельца')),
            ],
            options={
                'verbose_name': 'Право управления расселением',
                'verbose_name_plural': 'Права управления расселением',
                'ordering': ['scope'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('acquired_at__isnull', True), ('expires_at__isnull', True), ('heartbeat_at__isnull', True), ('lease_token__isnull', True), ('owner_access__isnull', True), ('owner_session_hash', '')), models.Q(('acquired_at__isnull', False), ('expires_at__isnull', False), ('heartbeat_at__isnull', False), ('lease_token__isnull', False), ('owner_access__isnull', False), models.Q(('owner_session_hash', ''), _negated=True)), _connector='OR'), name='settlement_control_lease_state_valid'), models.CheckConstraint(condition=models.Q(('owner_access__isnull', True), models.Q(('heartbeat_at__gte', models.F('acquired_at')), ('expires_at__gt', models.F('heartbeat_at'))), _connector='OR'), name='settlement_control_lease_time_valid'), models.CheckConstraint(condition=models.Q(('fencing_revision__gte', 0)), name='settlement_control_revision_nonnegative')],
            },
        ),
        migrations.RunPython(
            create_settlement_control_lease,
            remove_settlement_control_lease,
        ),
    ]
