# Generated by Django 6.0.6 on 2026-08-17 02:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0007_settlement_control_lease_and_event'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationAnchorCalendarSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('closed', 'Закрыт')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда подтверждён')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_slots', to='settlement.accommodationanchor', verbose_name='Жилищный якорь')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_accommodation_calendar_slots', to='users.employee', verbose_name='Кем подтверждён')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_accommodation_calendar_slots', to='users.employee', verbose_name='Кем закрыт')),
                ('closed_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_accommodation_calendar_slots', to='settlement.settlementrevision', verbose_name='Ревизия закрытия')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_calendar_slots', to='settlement.settlementrevision', verbose_name='Ревизия-основание')),
                ('watch_composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_calendar_slots', to='users.watchcomposition', verbose_name='Утверждённый состав вахты')),
                ('watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_calendar_slots', to='shifts.watchperiod', verbose_name='Конкретный период вахты')),
            ],
            options={
                'verbose_name': 'Календарный слот жилищного якоря',
                'verbose_name_plural': 'Календарные слоты жилищных якорей',
                'ordering': ['valid_from', 'anchor_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccommodationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('closed', 'Закрыто')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('basis_type', models.CharField(max_length=64, verbose_name='Тип основания')),
                ('basis_id', models.CharField(max_length=128, verbose_name='Идентификатор основания')),
                ('basis_snapshot', models.JSONField(verbose_name='Неизменяемый снимок основания')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда подтверждено')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда закрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('anchor_calendar_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_bindings', to='settlement.accommodationanchorcalendarslot', verbose_name='Календарный слот жилищного якоря')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_employee_accommodation_bindings', to='users.employee', verbose_name='Кем подтверждено')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_employee_accommodation_bindings', to='users.employee', verbose_name='Кем закрыто')),
                ('closed_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_employee_accommodation_bindings', to='settlement.settlementrevision', verbose_name='Ревизия закрытия')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_bindings', to='users.employee', verbose_name='Сотрудник')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_accommodation_bindings', to='settlement.settlementrevision', verbose_name='Ревизия-основание')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='settlement.employeeaccommodationbinding', verbose_name='Заменяет закрепление')),
            ],
            options={
                'verbose_name': 'Постоянное жилищное закрепление сотрудника',
                'verbose_name_plural': 'Постоянные жилищные закрепления сотрудников',
                'ordering': ['employee_id', 'valid_from', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='accommodationanchorcalendarslot',
            index=models.Index(fields=['anchor', 'status', 'valid_from'], name='anchor_slot_anchor_period_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationanchorcalendarslot',
            index=models.Index(fields=['watch_composition', 'status', 'valid_from'], name='anchor_slot_watch_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='accommodationanchorcalendarslot',
            constraint=models.UniqueConstraint(fields=('anchor', 'watch_period'), name='unique_anchor_slot_per_watch_period'),
        ),
        migrations.AddConstraint(
            model_name='accommodationanchorcalendarslot',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='anchor_slot_period_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='accommodationanchorcalendarslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('closed_revision__isnull', True), ('status', 'draft')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('closed_at__isnull', True), ('closed_by__isnull', True), ('closed_revision__isnull', True), ('status', 'confirmed')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('closed_at__isnull', False), ('closed_by__isnull', False), ('closed_revision__isnull', False), ('status', 'closed')), _connector='OR'), name='anchor_slot_lifecycle_metadata'),
        ),
        migrations.AddIndex(
            model_name='employeeaccommodationbinding',
            index=models.Index(fields=['employee', 'status', 'valid_from'], name='employee_binding_period_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeaccommodationbinding',
            index=models.Index(fields=['anchor_calendar_slot', 'status', 'valid_from'], name='slot_binding_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccommodationbinding',
            constraint=models.UniqueConstraint(fields=('employee', 'anchor_calendar_slot', 'valid_from'), name='unique_employee_slot_binding_start'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccommodationbinding',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='employee_binding_period_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccommodationbinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('closed_revision__isnull', True), ('status', 'draft')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('closed_at__isnull', True), ('closed_by__isnull', True), ('closed_revision__isnull', True), ('status', 'confirmed')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('closed_at__isnull', False), ('closed_by__isnull', False), ('closed_revision__isnull', False), ('status', 'closed')), _connector='OR'), name='employee_binding_lifecycle_metadata'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccommodationbinding',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('pk', models.F('supersedes_id')), _negated=True), _connector='OR'), name='employee_binding_not_self_supersede'),
        ),
    ]
