# Generated by Django 6.0.6 on 2026-08-17 03:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0008_m4_calendar_slots_and_bindings'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('version', models.PositiveIntegerField(verbose_name='Версия состава')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('superseded', 'Заменён новой версией')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('source_type', models.CharField(max_length=64, verbose_name='Тип источника')),
                ('source_id', models.CharField(max_length=128, verbose_name='Идентификатор источника')),
                ('source_snapshot', models.JSONField(verbose_name='Неизменяемый снимок источника')),
                ('input_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Отпечаток состава должен быть SHA-256 в нижнем регистре.', regex='^[0-9a-f]{64}$')], verbose_name='Отпечаток входного состава')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда утверждена')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда заменена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlement_cohorts', to='users.employee', verbose_name='Кем утверждена версия')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_cohorts', to='users.employee', verbose_name='Кем зафиксирована версия')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_cohorts', to='settlement.settlementrevision', verbose_name='Ревизия-основание')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='settlement.settlementcohort', verbose_name='Заменяет версию состава')),
                ('watch_composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_cohorts', to='users.watchcomposition', verbose_name='Утверждённый состав вахты')),
                ('watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_cohorts', to='shifts.watchperiod', verbose_name='Конкретный период вахты')),
            ],
            options={
                'verbose_name': 'Жилищная версия состава заезда',
                'verbose_name_plural': 'Жилищные версии составов заезда',
                'ordering': ['watch_period_id', 'version', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SettlementCohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('arrival_at', models.DateTimeField(verbose_name='Прибытие')),
                ('departure_at', models.DateTimeField(verbose_name='Выбытие')),
                ('participation_status', models.CharField(choices=[('participating', 'Участвует в заезде'), ('not_arriving', 'Не заезжает'), ('extended', 'Продление'), ('additional', 'Дополнительный сотрудник')], db_index=True, default='participating', max_length=16, verbose_name='Статус участия')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина изменения')),
                ('expected_schedule_regime', models.CharField(blank=True, max_length=64, verbose_name='Ожидаемый режим графика snapshot')),
                ('basis_type', models.CharField(max_length=64, verbose_name='Тип основания')),
                ('basis_id', models.CharField(max_length=128, verbose_name='Идентификатор основания')),
                ('basis_snapshot', models.JSONField(verbose_name='Неизменяемый снимок основания')),
                ('production_context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок производственного контекста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='settlement.settlementcohort', verbose_name='Версия состава заезда')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_cohort_memberships', to='users.employee', verbose_name='Сотрудник')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_cohort_members', to='settlement.settlementrevision', verbose_name='Ревизия-основание строки')),
            ],
            options={
                'verbose_name': 'Строка жилищного состава заезда',
                'verbose_name_plural': 'Строки жилищного состава заезда',
                'ordering': ['cohort_id', 'employee_id', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementcohort',
            index=models.Index(fields=['watch_period', 'status', 'version'], name='cohort_period_status_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementcohort',
            index=models.Index(fields=['watch_composition', 'status'], name='cohort_composition_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohort',
            constraint=models.UniqueConstraint(fields=('watch_period', 'version'), name='unique_cohort_watch_period_version'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohort',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('watch_period',), name='unique_approved_cohort_per_watch'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohort',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='cohort_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('status', 'draft'), ('superseded_at__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status', 'approved'), ('superseded_at__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status', 'superseded'), ('superseded_at__isnull', False)), _connector='OR'), name='cohort_lifecycle_metadata'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohort',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('pk', models.F('supersedes_id')), _negated=True), _connector='OR'), name='cohort_not_self_supersede'),
        ),
        migrations.AddIndex(
            model_name='settlementcohortmember',
            index=models.Index(fields=['employee', 'participation_status', 'arrival_at'], name='cohort_member_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementcohortmember',
            index=models.Index(fields=['cohort', 'participation_status'], name='cohort_member_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohortmember',
            constraint=models.UniqueConstraint(fields=('cohort', 'employee'), name='unique_employee_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohortmember',
            constraint=models.CheckConstraint(condition=models.Q(('departure_at__gt', models.F('arrival_at'))), name='cohort_member_period_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='settlementcohortmember',
            constraint=models.CheckConstraint(condition=models.Q(('participation_status__in', ['participating', 'not_arriving', 'extended', 'additional'])), name='cohort_member_status_valid'),
        ),
    ]
