# Generated by Django 6.0.6 on 2026-08-17 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0009_m5_authoritative_cohorts'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementResident',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'stable_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name='Стабильный идентификатор',
                    ),
                ),
                (
                    'resident_type',
                    models.CharField(
                        choices=[
                            ('EMPLOYEE', 'Внутренний сотрудник'),
                            ('CONTRACTOR', 'Сотрудник подрядчика'),
                            ('BUSINESS_TRIP', 'Командированный'),
                            ('EXTERNAL_OTHER', 'Другой внешний жилец'),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name='Тип жильца',
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='ФИО внешнего жильца',
                    ),
                ),
                (
                    'photo',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='settlement_residents/',
                        verbose_name='Фото внешнего жильца',
                    ),
                ),
                (
                    'position_title',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Должность или профессия внешнего жильца',
                    ),
                ),
                (
                    'organization',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Организация внешнего жильца',
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name='Телефон внешнего жильца',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('ACTIVE', 'Активен'), ('ARCHIVED', 'В архиве')],
                        db_index=True,
                        default='ACTIVE',
                        max_length=16,
                        verbose_name='Статус карточки',
                    ),
                ),
                (
                    'revision',
                    models.PositiveBigIntegerField(
                        default=1,
                        verbose_name='Ревизия карточки',
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Когда архивирована',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                (
                    'created_by_access',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_settlement_residents',
                        to='users.employeeaccess',
                        verbose_name='Доступ создателя',
                    ),
                ),
                (
                    'employee',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='settlement_resident',
                        to='users.employee',
                        verbose_name='Внутренний сотрудник',
                    ),
                ),
                (
                    'updated_by_access',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='updated_settlement_residents',
                        to='users.employeeaccess',
                        verbose_name='Доступ последнего редактора',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Жилец settlement',
                'verbose_name_plural': 'Жильцы settlement',
                'ordering': ['resident_type', 'pk'],
                'indexes': [
                    models.Index(
                        fields=['status', 'resident_type'],
                        name='resident_status_type_idx',
                    ),
                    models.Index(
                        fields=['organization', 'status'],
                        name='resident_org_status_idx',
                    ),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('revision__gte', 1)),
                        name='settlement_resident_revision_positive',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('archived_at__isnull', True), ('status', 'ACTIVE')),
                            models.Q(('archived_at__isnull', False), ('status', 'ARCHIVED')),
                            _connector='OR',
                        ),
                        name='settlement_resident_archive_state_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('employee__isnull', False),
                                ('full_name', ''),
                                ('organization', ''),
                                ('phone', ''),
                                ('position_title', ''),
                                ('resident_type', 'EMPLOYEE'),
                                models.Q(
                                    ('photo__isnull', True),
                                    ('photo', ''),
                                    _connector='OR',
                                ),
                            ),
                            models.Q(
                                ('created_by_access__isnull', False),
                                ('employee__isnull', True),
                                (
                                    'resident_type__in',
                                    ['CONTRACTOR', 'BUSINESS_TRIP', 'EXTERNAL_OTHER'],
                                ),
                                models.Q(('full_name', ''), _negated=True),
                                models.Q(('position_title', ''), _negated=True),
                                models.Q(('organization', ''), _negated=True),
                                models.Q(('phone', ''), _negated=True),
                            ),
                            _connector='OR',
                        ),
                        name='settlement_resident_subject_valid',
                    ),
                ],
            },
        ),
    ]
