# Generated by Django 6.0.6 on 2026-08-17 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def reverse_fail_closed(apps, schema_editor):
    using = schema_editor.connection.alias
    Application = apps.get_model('settlement', 'SettlementPreviewApplication')
    Occupancy = apps.get_model('settlement', 'EmployeeBedOccupancy')
    application_count = Application.objects.using(using).count()
    provenance_count = (
        Occupancy.objects.using(using)
        .filter(
            models.Q(source_application__isnull=False)
            | models.Q(source_preview_placement__isnull=False)
            | models.Q(replaced_by_application__isnull=False)
            | models.Q(replaced_by_occupancy__isnull=False)
        )
        .count()
    )
    if application_count or provenance_count:
        raise RuntimeError(
            'settlement.0014 reverse would destroy Apply history: '
            f'applications={application_count}, provenance_occupancies={provenance_count}.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0013_resident_occupancy_subject'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPreviewApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('action', models.CharField(choices=[('created', 'Создано AUTO-размещение'), ('reused', 'Переиспользовано AUTO-размещение'), ('replaced_auto', 'Заменено прежнее AUTO-размещение'), ('replaced_manual', 'Заменена ручная корректировка')], max_length=24, verbose_name='Действие Apply')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Связь Application с occupancy',
                'verbose_name_plural': 'Связи Application с occupancy',
                'ordering': ['application_id', 'occupancy_id', 'action', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='cohort_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_occupancies', to='settlement.settlementcohortmember', verbose_name='Строка состава occupancy'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='replaced_by_occupancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_occupancy_history', to='settlement.employeebedoccupancy', verbose_name='Ручная occupancy, заменившая эту строку'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Ручное'), ('auto', 'Авторосселение')], db_index=True, default='manual', max_length=16, verbose_name='Источник размещения'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='source_preview_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_occupancies', to='settlement.settlementpreviewplacement', verbose_name='Placement-источник AUTO'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='watch_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_occupancies', to='shifts.watchperiod', verbose_name='Период вахты occupancy'),
        ),
        migrations.CreateModel(
            name='SettlementPreviewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Применено')),
                ('resolver_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 входов resolver')),
                ('normalized_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')], verbose_name='SHA-256 нормализованного результата')),
                ('confirm_replace_manual', models.BooleanField(default=False)),
                ('created_occupancy_count', models.PositiveIntegerField(default=0)),
                ('closed_occupancy_count', models.PositiveIntegerField(default=0)),
                ('replaced_occupancy_count', models.PositiveIntegerField(default=0)),
                ('result_snapshot', models.JSONField(verbose_name='Неизменяемый снимок результата Apply')),
                ('applied_by_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_preview_applications', to='users.employeeaccess', verbose_name='Точный доступ применившего')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_preview_applications', to='settlement.settlementcohort', verbose_name='Утверждённый состав заезда')),
                ('preview_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='settlement.settlementpreviewrun', verbose_name='Применённый preview')),
                ('watch_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_preview_applications', to='shifts.watchperiod', verbose_name='Период вахты')),
            ],
            options={
                'verbose_name': 'Применение сохранённого preview',
                'verbose_name_plural': 'Применения сохранённых preview',
                'ordering': ['watch_period_id', 'applied_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='replaced_by_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_occupancies', to='settlement.settlementpreviewapplication', verbose_name='Application, заменивший размещение'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='source_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_occupancies', to='settlement.settlementpreviewapplication', verbose_name='Application-источник AUTO'),
        ),
        migrations.AddConstraint(
            model_name='employeebedoccupancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_application__isnull', True), ('source_kind', 'manual'), ('source_preview_placement__isnull', True)), models.Q(('cohort_member__isnull', False), ('source_application__isnull', False), ('source_kind', 'auto'), ('source_preview_placement__isnull', False), ('watch_period__isnull', False)), _connector='OR'), name='occupancy_auto_provenance_complete'),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy_items', to='settlement.settlementpreviewapplication', verbose_name='Применение preview'),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='occupancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='settlement.employeebedoccupancy', verbose_name='Историческая или созданная occupancy'),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='preview_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='settlement.settlementpreviewplacement', verbose_name='Строка preview'),
        ),
        migrations.AddIndex(
            model_name='settlementpreviewapplication',
            index=models.Index(fields=['watch_period', 'applied_at'], name='preview_apply_period_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewapplicationitem',
            constraint=models.UniqueConstraint(fields=('application', 'occupancy', 'action'), name='unique_apply_occupancy_action'),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_fail_closed),
    ]
