# Generated by Django 6.0.6 on 2026-08-18 05:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def refuse_reverse_with_corrections(apps, schema_editor):
    correction_model = apps.get_model('settlement', 'SettlementPreviewCorrection')
    rows = correction_model.objects.using(schema_editor.connection.alias).order_by('pk')
    count = rows.count()
    if count:
        sample_pks = list(rows.values_list('pk', flat=True)[:20])
        raise RuntimeError(
            'Нельзя откатить settlement.0017: существуют точечные исправления '
            f'(count={count}, pk={sample_pks}).'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_equipment_assignment_provenance'),
        ('settlement', '0016_shift_scoped_apply_and_occupancy'),
        ('shifts', '0013_unique_open_oup_period'),
        ('users', '0017_employee_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPreviewCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Стабильный идентификатор')),
                ('work_shift', models.CharField(choices=[('day', 'Дневная смена'), ('night', 'Ночная смена')], max_length=16)),
                ('action', models.CharField(choices=[('move', 'Переставить'), ('exclude', 'Исключить'), ('restore', 'Вернуть исходное решение')], max_length=16)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source_snapshot', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='^[0-9a-f]{64}$')])),
            ],
            options={
                'ordering': ['preview_run_id', 'resident_id', 'work_shift', 'created_at', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='employeebedoccupancy',
            name='occupancy_auto_provenance_complete',
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='correction_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='effective_decision_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='preview_unresolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='settlement.settlementpreviewunresolved'),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='source_decision_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='settlementpreviewapplicationitem',
            name='action',
            field=models.CharField(choices=[('created', 'Создано AUTO-размещение'), ('reused', 'Переиспользовано AUTO-размещение'), ('replaced_auto', 'Заменено прежнее AUTO-размещение'), ('replaced_manual', 'Заменена ручная корректировка'), ('excluded', 'Жилец намеренно исключён из применения')], max_length=24, verbose_name='Действие Apply'),
        ),
        migrations.AlterField(
            model_name='settlementpreviewapplicationitem',
            name='occupancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='settlement.employeebedoccupancy', verbose_name='Историческая или созданная occupancy'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='actor_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_preview_corrections', to='users.employeeaccess'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='preview_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='settlement.settlementpreviewrun'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_corrections', to='settlement.settlementresident'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='source_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='settlement.settlementpreviewplacement'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='source_unresolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='settlement.settlementpreviewunresolved'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='settlement.settlementpreviewcorrection'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='target_calendar_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_corrections', to='settlement.accommodationanchorcalendarslot'),
        ),
        migrations.AddField(
            model_name='settlementpreviewcorrection',
            name='target_physical_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_corrections', to='settlement.physicalbed'),
        ),
        migrations.AddField(
            model_name='employeebedoccupancy',
            name='source_preview_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_occupancies', to='settlement.settlementpreviewcorrection', verbose_name='Точечное исправление-источник AUTO'),
        ),
        migrations.AddField(
            model_name='settlementpreviewapplicationitem',
            name='effective_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='settlement.settlementpreviewcorrection'),
        ),
        migrations.AddConstraint(
            model_name='employeebedoccupancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_application__isnull', True), ('source_kind', 'manual'), ('source_preview_correction__isnull', True), ('source_preview_placement__isnull', True)), models.Q(('cohort_member__isnull', False), ('source_application__isnull', False), ('source_kind', 'auto'), ('watch_period__isnull', False), models.Q(('source_preview_placement__isnull', False), ('source_preview_correction__isnull', False), _connector='OR')), _connector='OR'), name='occupancy_auto_provenance_complete'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewapplicationitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'excluded'), ('effective_correction__isnull', False), ('occupancy__isnull', True)), models.Q(models.Q(('action', 'excluded'), _negated=True), ('occupancy__isnull', False)), _connector='OR'), name='apply_item_occupancy_by_action'),
        ),
        migrations.AddIndex(
            model_name='settlementpreviewcorrection',
            index=models.Index(fields=['preview_run', 'resident', 'work_shift', 'created_at'], name='preview_corr_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_placement__isnull', False), ('source_unresolved__isnull', True)), models.Q(('source_placement__isnull', True), ('source_unresolved__isnull', False)), _connector='OR'), name='preview_corr_source_xor'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'move'), ('target_calendar_slot__isnull', False), ('target_physical_bed__isnull', False)), models.Q(('action__in', ['exclude', 'restore']), ('target_calendar_slot__isnull', True), ('target_physical_bed__isnull', True)), _connector='OR'), name='preview_corr_target_by_action'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewcorrection',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('pk', models.F('supersedes_id')), _negated=True), _connector='OR'), name='preview_corr_not_self'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'restore'), _negated=True), ('supersedes__isnull', False), _connector='OR'), name='preview_corr_restore_has_previous'),
        ),
        migrations.AddConstraint(
            model_name='settlementpreviewcorrection',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_preview_corr_successor'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            refuse_reverse_with_corrections,
        ),
    ]
