# Generated by Django 6.0.6 on 2026-07-01 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalStateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ состояния')),
                ('version', models.PositiveBigIntegerField(default=0, verbose_name='Версия')),
                ('reason', models.CharField(blank=True, max_length=128, verbose_name='Причина изменения')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Версия оперативного состояния',
                'verbose_name_plural': 'Версии оперативного состояния',
                'ordering': ['key'],
            },
        ),
    ]
