# Generated by Django 6.0.6 on 2026-07-01 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='Ключ состояния')),
                ('version', models.PositiveBigIntegerField(verbose_name='Версия события')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип события')),
                ('object_type', models.CharField(blank=True, max_length=128, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('reason', models.CharField(blank=True, max_length=128, verbose_name='Причина изменения')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие оперативного состояния',
                'verbose_name_plural': 'События оперативного состояния',
                'ordering': ['version'],
                'indexes': [models.Index(fields=['key', 'version'], name='core_operat_key_16c958_idx'), models.Index(fields=['key', 'event_type'], name='core_operat_key_6b01db_idx')],
            },
        ),
    ]
