# Generated by Django 6.0.8 on 2026-10-05 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offline_field_event'),
        ('downtimes', '0005_downtime_actor_subject'),
        ('references', '0010_remove_obsolete_cargo_aliases'),
        ('shifts', '0020_shiftclientaction_request_signature'),
        ('trips', '0017_free_bucket_accepted_by_driver_action'),
        ('users', '0026_native_push_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Web Push'), ('native', 'Native Push')], max_length=16, verbose_name='Канал')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='ID подписки')),
                ('target_fingerprint', models.CharField(max_length=64, verbose_name='Отпечаток адресата')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая попытка')),
                ('lease_token', models.CharField(blank=True, max_length=32, verbose_name='Владелец попытки')),
                ('leased_until', models.DateTimeField(blank=True, null=True, verbose_name='Аренда до')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток доставки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('terminal_reason', models.CharField(blank=True, max_length=64, verbose_name='Причина завершения')),
                ('last_error', models.CharField(blank=True, max_length=128, verbose_name='Последняя ошибка')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': 'Доставки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_key', models.CharField(max_length=192, unique=True, verbose_name='Ключ эффекта')),
                ('payload', models.JSONField(editable=False, verbose_name='Снимок уведомления')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Намерение уведомления',
                'verbose_name_plural': 'Намерения уведомлений',
            },
        ),
        migrations.AddField(
            model_name='offlinefieldevent',
            name='input_envelope',
            field=models.JSONField(default=dict, editable=False, verbose_name='Исходный серверный конверт'),
        ),
        migrations.AddField(
            model_name='offlinefieldevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка'),
        ),
        migrations.AddField(
            model_name='offlinefieldevent',
            name='retry_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Попыток применения'),
        ),
        migrations.AddIndex(
            model_name='offlinefieldevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='off_evt_retry_due'),
        ),
        migrations.AddField(
            model_name='notificationintent',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_intent', to='users.pushnotification', verbose_name='Текст для приложения'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.notificationintent'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['available_at', 'leased_until'], name='notification_delivery_due'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('intent', 'channel', 'target_id'), name='notification_target_once'),
        ),
    ]
